### ISSUE TITLE
Actualización para PHP 7.1

### ISSUE THREAD

**Issue by dhenriquez** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#1]
Estimados, tienen pensando hacer una actualización para PHP 7.1 para funcionar sin la libreria MCrypt?

**Comment by matiaslopezd** [comment]
@dhenriquez desde la versión [2.0.1](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/releases) si se puede, aunque obvio descarga la [2.1.4](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/releases/tag/2.1.4). Al fin!!
