### ISSUE TITLE
Error Fatal en /libwebpay/Telemetry/PluginVersion.php: failed to load external entity

### ISSUE THREAD

**Issue by TCattd** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#104]
Al guardar la configuración del plugin, arroja el siguiente error (WP) https://tppr.me/sIQfC

Log:

```
Detalles del error
==================
Se ha producido un error del tipo E_ERROR en la línea 24 del archivo /home/***/public_html/wp-content/plugins/woocommerce-transbank/libwebpay/Telemetry/PluginVersion.php. Mensaje de error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://www.cumbregroup.com/tbk-webservice/PluginVersion.php?wsdl' : failed to load external entity "http://www.cumbregroup.com/tbk-webservice/PluginVersion.php?wsdl"
 in /home/***/public_html/wp-content/plugins/woocommerce-transbank/libwebpay/Telemetry/PluginVersion.php:24
Stack trace:
#0 /home/***/public_html/wp-content/plugins/woocommerce-transbank/libwebpay/Telemetry/PluginVersion.php(24): SoapClient->SoapClient('http://www.cumb...')
#1 /home/***/public_html/wp-content/plugins/woocommerce-transbank/webpay.php(164): Transbank\Telemetry\PluginVersion->__construct()
#2 /home/***/public_html/wp-includes/class-wp-hook.php(288): WC_Gateway_Transbank->registerPluginVersion('')
#3 /home/***/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(true, Array)
#4 /home/***/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /home/***
```

**Para reproducir**

1. Abrir la configuración de Transbank dentro de WooCommerce.
2. Guardar.
3. Arrojará un error 

**Comportamiento observado**

Cae el sitio y se gatilla la protección de WP ante errores fatales.

**Comportamiento esperado**

No debería caer el sitio.

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 2.5.3
- WooCommerce: 4.0.0
- PHP: 7.3.15

**Contexto adicional**

Esto ocurre ocasionalmente. No es constante el error. Pero pasa. Y cuando ocurre, es siempre al intentar contactar al host http://www.cumbregroup.com para la telemetría que pusieron en el plugin.

Otras dudas aparte serían:

* ¿Por qué telemetría del plugin?

* (Entendiendo que la telemetría sirve, y si tiene que estar) ¿Por qué sin opción a desactivarla?.
GDPR en mente. Si un Europeo intenta comprar con una tienda que use este plugin, podría poner en problemas legales a quién administra la tienda.

* (Y una importante) ¿Por qué en un servidor que no es de transbank? (cumbregroup.com)

**Comment by gonzunigad** [comment]
Gracias por reportar el error. Solo al momento de guardar tu configuración, si tu ambiente está configurado como 'Producción', este envía a un API: tu código de comercio, la versión del plugin que usas y la versión del ecommerce. 
Esto no envía información de compras ni se ejecuta en otro momento que no sea el indicado (como cuando un comprador realiza algún proceso en la tienda).  

Este PR https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/pull/105 resuelve el problema, para evitar que se arroje algún error si el API tiene problemas :)

**Comment by TCattd** [comment]
@gonzunigad gracias por la celeridad.

La última duda importante queda en el aire eso si: ¿Por qué en un servidor que no es de Transbank? (cumbregroup.com).

**Comment by gonzunigad** [comment]
Hola @TCattd . Esa url es del proveedor que entrega la herramientas que usan en Transbank para revisar que plugin tiene instalado un comercio cuando este requiere de soporte.

**Comment by gonzunigad** [comment]
Ahora que ese PR está mezclado, cierro este issue :)
