### ISSUE TITLE
Imagen de Webpay es gigante

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#107]
Hola!

La imagen por defecto que se muestra al pagar es gigante de 1000x1200px deberían dejarla en 150x150px como lo tienen los demás plugins como Khipu por ejemplo o 200x100 de Flow.

![image](https://user-images.githubusercontent.com/31737938/77196226-af452c80-6ac1-11ea-962b-485ca02a203f.png)

Saludos!

Sven

**Comment by gonzunigad** [comment]
El PR de @saengate debería resolver el problema.
