### ISSUE TITLE
Pedido pasa de "Procesando" a "Pendiente de pago"

### ISSUE THREAD

**Issue by aquezada** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#109]
Un error conocido en versiones anteriores, el pedido pasa de Procesando a Pendiente de pago. 

Adjunto screenshot de la linea de tiempo para poder hacerme entender. 

<img width="251" alt="Screenshot 2020-03-28 16 43 46" src="https://user-images.githubusercontent.com/18424/77832238-56097880-7113-11ea-84fa-dc4a9fdd5af0.png">

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: Mismo bug en 2.6.0 y 2.6.1
- Woocommerce: 4.0.1
- PHP: 7.2.5

**Comment by aquezada** [comment]
Existe una opción que no conocía en configuración: Estado de pedido después del pago

Independiente que decía "Procesando", igual vuelve a "Pendiente de pago".

Lo que hice fue, marcar otro estado, guardar. Y nuevamente seleccionar "Procesando" y volver a guardar.

Con eso, sé soluciono ;).

**Comment by KraptorChile** [comment]
> Existe una opción que no conocía en configuración: Estado de pedido después del pago
> 
> Independiente que decía "Procesando", igual vuelve a "Pendiente de pago".
> 
> Lo que hice fue, marcar otro estado, guardar. Y nuevamente seleccionar "Procesando" y volver a guardar.
> 
> Con eso, sé soluciono ;).

Me pasó lo mismo, apliqué la solución que @aquezada mencionó y se resolvió.

**Comment by sonda123** [comment]
Acabo de actualizar el plugin de transbank y empezó a cambiar de procesando para pendiente de pago. 
estoy con Woocommerce 4.1
wordpress 5.4 
php 7.2.30
webpay transbank 2.7.1 

![Captura de Tela 2020-05-10 às 14 31 07](https://user-images.githubusercontent.com/47185145/81507418-4c0a9600-92cb-11ea-9be7-b02c38ade98f.jpg)
![Captura de Tela 2020-05-10 às 14 31 14](https://user-images.githubusercontent.com/47185145/81507419-4e6cf000-92cb-11ea-84bb-3ef08d0bf328.jpg)

**Comment by sonda123** [comment]
Gracias Hice el procedimiento, en las configuraciones del plugin webpay y me funcionó!
