### ISSUE TITLE
Web Services no envía método de pago correcto

### ISSUE THREAD

**Issue by dnewscience** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#112]
**Describe el bug**

Actualizamos el plug in y el Webservices no envía el tipo de pago correcto.

**Para reproducir**

1. Al ser el pedido marcado como completado, nuestro webservices envía todos los pedidos como crédito.

**Comportamiento observado**

Se recibe como "Webpay Credito" cuando debería ser "Webpay Debito"

Este es el código actual en nuestro archivo WS:
`$vTipoPago = "";
if ( $order->payment_details->method_id == "transbank"){
	$vTipoPago = "Webpay Credito";
	$SQLW = "SELECT * FROM ". $wpdb->prefix ."webpay WHERE idOrder = '$order_id'";
 

	$get_webpay = $wpdb->get_results($SQLW);
	foreach ( $get_webpay as $webpay ){
		$vCodAuto = $webpay->TBK_CODIGO_AUTORIZACION;
		$vNumTarjeta = $webpay->TBK_FINAL_NUMERO_TARJETA;
		$vFecCont = $webpay->TBK_FECHA_CONTABLE;
		$tipoPAGO = $webpay->TBK_TIPO_PAGO;
		if ( $webpay->TBK_TIPO_PAGO == "VD"){
			$vTipoPago = "Webpay Debito";
		}`

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 2.2.6.
- Woocommerce: 3.8.1.
- PHP: 7.2.29.

**Comment by gonzunigad** [comment]
Hola @dnewscience . Gracias por reportar el issue!. 
¿A que WebService te refieres? 
No me queda muy claro  en que parte no se está guardando/enviando bien la información que comentas. ¿Me podrías específicar mejor de que manera ver y replicar el error para poder resolver esto?

**Comment by dnewscience** [comment]
Necesitamos que la web envíe el tipo de pago (débito o crédito) a nuestro CRM junto con la información del pedido, pero al actualizar el plug in ya no funciona el código y no logro ver qué fue lo que cambió con el nuevo plug in.

**Comment by gonzunigad** [comment]
¿cómo tienen hecha esa integración con el CRM? ¿Dé donde sacan los datos?
