### ISSUE TITLE
Autorizaciónes Denegadas y relación con Borrar Caché-Cookies

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#115]
Estimados,

Tengo una duda/problema.
Llevo usando este plugin (y actualizándolo) desde que se creó. 
Monitoreando las transacciones me ha pasado innumerables veces que un cliente intentando realizar la compra obtiene como respuesta final "**Autorización Denegada**" mostrado en el Reporte transaccional de Transbank.
Descubrimos que si tomábamos contacto con el cliente y le indicabamos volver a intentar la compra, pero antes **borrando las Cookies y el Caché**; muchas veces la compra sí lograba autorizarse.

Mi duda, es: ¿Por qué pasa esto? ¿O no tiene nada que ver?
Actualmente usamos Cloudflare, hosting en Siteground, Wp-rocket para cachear la página web. 

Desde ya, muchas gracias por su tiempo.

Sven

**Comment by gonzunigad** [comment]
Hola @svenms. Gracias por el reporte! 
¿Estás usando la última versión del plugin? Hace poco hicimos un cambio para no usar varaibles de sesión, que podría afectar positivamentet en este caso.

**Comment by svenms** [comment]
Hola @gonzunigad . Estoy usando la última versión. Puede que últimamente haya dejado de suceder. 
Voy a monitorearlo de más cerca ahora para ver si efectivamente dejó de suceder.

Gracias por tu respuesta.

**Comment by gonzunigad** [comment]
Hola, como no hemos tenido mayor detalle de eso, cerraré el issue, pero si tienes más observaciones, lo podemos reabrir.
