### ISSUE TITLE
Error con plugins actualizados en PHP 7

### ISSUE THREAD

**Issue by PPastene** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#12]
Estoy usando la versión 2.1.4 del plugin con la versión de PHP 7.0.25, Wordpress 5.0.2 y Woocommerce 3.5.2. Al momento de finalizar la compra me aparece el siguiente error

Fatal error: Uncaught SoapFault exception: [Client] SoapClient::SoapClient(): 'uri' option is required in nonWSDL mode in /home/tubellezavende/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php:16 Stack trace: #0 /home/tubellezavende/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php(16): SoapClient->SoapClient(NULL, Array) #1 /home/tubellezavende/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/WebPayNormal.php(66): Transbank\Webpay\WSSecuritySoapClient->__construct(NULL, '-----BEGIN RSA ...', '-----BEGIN CERT...', Array) #2 /home/tubellezavende/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/Webpay.php(74): Transbank\Webpay\WebPayNormal->__construct(Object(Transbank\Webpay\Configuration)) #3 /home/tubellezavende/public_html/wp-content/plugins/woocommerce-transbank/libwebpay/Transbank in /home/tubellezavende/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php on line 16

Usando la versión 5.6 de PHP no aparece el error pero tampoco aparece el botón de pago para redirigir a Webpay 

Estas son las versiones de las extensiones en PHP 7.0.25
openssl: 1.0.1e-fips 11 Feb 2013
SimpleXML: 7.0.25
soap: 7.0.25
dom: 20031129

Y así las muestra en PHP 5.6
openssl: 1.0.1e-fips 11 Feb 2013
SimpleXML: 0.1
soap: PHP Extension compiled ver:5.6.30
dom: 20031129

**Comment by leosoto** [comment]
Fixed in #20 and released in v2.1.6.
