### ISSUE TITLE
Mejora para la Redirección de Pedido Cancelado

### ISSUE THREAD

**Issue by GfloresFG** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#120]
**Describe el bug**

Al momento de anular una compra el cliente es redirigido a la misma página de "/gracias" a la que iría si hubierse realizado la compra. 
Esto es un problema, ya que afecta al traqueo de los clientes que ya han comprado, con los que no.

**Comportamiento observado**

Link de "Anular compra y vovler a..." redirige a página de "/gracias"

**Comportamiento esperado**

Link de "Anular compra y vovler a..." debería redirigir a página de "/compra-fallida"

**Capturas de pantalla**

https://drive.google.com/open?id=1haIxVgiIg7rlGrkzmxoHeim3EtNr4EB9

**Versiones (por favor agrega aquí la siguiente información):**

- Plugin: 2.7.1
- Woocommerce: 4.1.0
- PHP: 7.1.33

**Comment by svaldesm** [comment]
Tengo el mismo problema, es confuso para las clientas

**Comment by GfloresFG** [comment]
demaaas bro. ¿Como podemos hacer para dejar más constancia? es un cacho pal trackeo esa redirección

**Comment by gonzunigad** [comment]
Hola! Gracias por proponer esta mejora. Voy a revisar como redirigir a esa página de compra fallida. ¿han intentado hacer el cambio modificarndo el plugin? Si lo lograron podrían generar algun PR para mezclarlo :)
Si no, me podrían comentar a que página corresponde esa '/compra-fallida'.

**Comment by gonzunigad** [comment]
¿Les parece razonable que lleve a esta pantalla con este mensaje? 
![image](https://user-images.githubusercontent.com/1103494/83444953-2c721380-a41a-11ea-8d6a-b3c0ac390005.png)

**Comment by svaldesm** [comment]
@gonzunigad mi mayor problema no tiene que ver tanto con la redirección, si no con el hecho de que el carro se vacía. 

Hoy por hoy, si intentas hacer un pago con Webpay y le pones "anular", te lleva a `checkout/order-pay/` que me parece la ruta apropiada. Es la vista que estás mostrando tú Gonzalo.
El problema es que si lo haces dos veces, ahí te lleva a `checkout/order-received` que no es lo deseado. 

Respecto al carro, tal como te comenté por Slack, creo que la idea es que no se vacíe nunca a menos que la transacción sea exitosa. No sé cómo se hace eso, estoy hablando estrictamente de lo que sería deseable para mi como usuario de los comercios.

Muchas gracias por darse el tiempo de pedir feedback y considerarnos para el desarrollo.

Saludos!

**Comment by svaldesm** [comment]
@GfloresFG en todo caso, respecto al trackeo, si lo estás haciendo por url visitada, no te lo recomiendo. 
Te sugiero que uses el plugin GTM4WP para agregar una capa de dataLayer a tu tienda y luego lo manejas por eventos. Es mucho más preciso, completo y versátil. 

Como referencia para instalarlo: https://gtm4wp.com/how-to-articles/how-to-setup-enhanced-ecommerce-tracking

Un abrazo!

**Comment by truchosky** [comment]
lo mejor sería redirigir nuevamente al checkout, no al "order-received" junto con el mensaje de error que dejó @gonzunigad , si falló o fue cancelado por el cliente. En ese caso podría ser algo mas genérico como: "hubo un problema con tu pago, favor intentarlo nuevamente"

**Comment by gonzunigad** [comment]
Este PR debería resolver este tema, junto con otros temas ded estabilidad. 
Ahora, tanto si la compra es fallida como si la compra es anulada por el usuario, se llega a la página del carrito con un mensaje similar al que posteé más arriba. 
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/pull/124

**Comment by gonzunigad** [comment]
@truchosky  @GfloresFG  @svaldesm 
Sería ideal si me ayudan a probar este PR. Tengo un ZIP con esta versión actualizada. Agradecería me ayuden a confirmar que se resuelve este issue 👍 

[woocommerce-transbank.zip](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/files/4748794/woocommerce-transbank.zip)

**Comment by gonzunigad** [comment]
Resuelto en versión 2.7.2 recién publicada.

**Comment by truchosky** [comment]
creo que introduce otro bug, al completar el pedido y pagar correctamente el articulo nunca se remueve del carro, alguien más con ese comportamiento?

**Comment by gonzunigad** [comment]
Hola! En base al otro issue que dejaste, veo que esto no pasa de manera global. Si tienes más info, comentala en el issue que creaste. Debe ser algo relacionado con algun otro plugin que tengas o alguna configuración.
