### ISSUE TITLE
El plugin no ha podido activarse porque ha provocado un error fatal

### ISSUE THREAD

**Issue by francisco-sanchez-p** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#121]
Hola a todos, hoy mi sitio se fue a blanco y luego de renombrar la carpeta plugins y comenzar a probar qué plugin fue el que falló me encontré que el plugin de Transbank ya no está operativo arrojando el siguiente error:

El plugin no ha podido activarse porque ha provocado un error fatal.

Warning: require_once(TransbankSdkWebpay.php): failed to open stream: No such file or directory in /home/melivacl/public_html/wp-content/plugins/woocommerce-transbank/libwebpay/HealthCheck.php on line 6

Fatal error: require_once(): Failed opening required 'TransbankSdkWebpay.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/melivacl/public_html/wp-content/plugins/woocommerce-transbank/libwebpay/HealthCheck.php on line 6

Si alguien puede orientarme se lo agradeceré un montón!

**Comment by gonzunigad** [comment]
Hola @francisco-sanchez-p . ¿Pudiste resolver este error? Me parece extraño que no encuentre el archivo TransbankSdkWebpay.php que está dentro del plugin. ¿Dedspués de que pasó eso?
Acá te recomendaría resintalarlo.

**Comment by gonzunigad** [comment]
Como no hemos podido recplicar el error, y no hay respuesta, dejaré este issue como cerrado, pero si tienen más info al respecto, encantado de volver a abrirlo.
