### ISSUE TITLE
Órdenes Fallidas, pero los clientes si pagaron

### ISSUE THREAD

**Issue by toby12222** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#122]
Estimados, en algunas órdenes de compra los pedidos son pagados y se reduce el inventario, pero de inmediato aparece como que fue cancelado por el cliente, pero efectivamente el cliente si pago.

Saludos

**Comment by svaldesm** [comment]
Me ocurre lo mismo, tal como le dije a @gonzunigad hace unos días y lo ha estado revisando. 
En mi caso, algunas veces pasan de Procesando a Completado y luego a Fallido. Otras veces el proceso es al revés, pero es confuso para los clientes.

**Comment by gonzunigad** [comment]
Hola @toby12222, @svaldesm. Me interesa resolver este punto. Nos han reportado este error, pero aún no tenemos claro bajo que caso de brode sucede, por lo tanto no podemos replicarlo. ¿Tienen algo de info al respecto que nnos pueda ayudar?

**Comment by gonzunigad** [comment]
Este PR debería reesolver el problema: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/pull/124

**Comment by gonzunigad** [comment]
Resuelto en versión 2.7.2 :)
