### ISSUE TITLE
Mejorar opción de traducciones

### ISSUE THREAD

**Issue by svaldesm** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#126]
Hola! Se pasaron con el último release, soluciona varias cosas que a nosotros al menos nos sirven un montón. 

Sería bueno que los textos se puedan traducir, por ejemplo los mensajes de FinalProcessController.php a través de Loco Translate para modificarlos. 
Lo mismo con el title y description de Webpay. Al menos a mí no me gusta el que viene por defecto y lo tengo que modificar con cada nuevo release, lo cual es un poco tedioso.

Saludos y gracias por el trabajo que hacen, nos sirve muchísimo!

**Comment by ffiebig** [comment]
Gracias por la sugerencia @svaldesm. Tenemos un backlog de mejora para este tipo de cosas pero tambien existe la alternativa de que nos ayudes con un Pull Request haciendo el cambio y luego lo revisamos. 

Si te interesa aportar puedes proponer una solución, la discutimos por aquí mismo y luego puedes enviarnos un PR.

**Comment by gonzunigad** [comment]
Hola! Esto se resolvió en el último Release :)
