### ISSUE TITLE
Error en instalación en Wordpress.com

### ISSUE THREAD

**Issue by cristiandelamaza** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#13]
Al instalar e intentar activar elplug-in en un sitio hosteado en Wordpress.com me tira el siguiente  error:

El plugin no ha podido activarse porque ha provocado un error fatal.

Fatal error: require_once(): Failed opening required '/wordpress/core/5.0.2/wp-content/plugins/woocommerce-transbank/vendor/autoload.php' (include_path='/:.') in /wpcom-152712965/wp-content/plugins/woocommerce-transbank-1/webpay.php on line 26

Tengo conocimientos muy básicos en programación por lo que no logro identificar el problema. ¿Qué se uede hacer para corregirlo?

**Comment by lmatab** [comment]
Hola @cristiandelamaza , tenia el mismo error, para solucionarlo verifica que el archivo con el que instalastes no termine en (#) ya que cuando wordpress lo trata de instalar no consigue hacerlo de forma correcta ya que considera esa terminacion del  archivo como el nombre del mismo, borra de la carpeta descargas de tu computador otras versiones que tengas del  para que no te pase e intenta nuevamente.

**Comment by leosoto** [comment]
@cristiandelamaza Se resolvió el problema con lo sugerido por @lmatab ?

**Comment by goncafa** [comment]
Este issue es el mismo reportado aquí: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/issues/18

Se hará follow up a este issue también cuando este validado y/o corregido el tema.

**Comment by cristiandelamaza** [comment]
Muchas gracias, esto sí resolvió el error. Borrando el (2) del final del nombre del plug in se instaló correctamente.
Saludos,
