### ISSUE TITLE
Carro no se vacía

### ISSUE THREAD

**Issue by truchosky** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#133]
creo que éste pull [124](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/pull/124) si bien resolvió lo que ahí se discutía introdujo otro bug, al completar el pedido el carro no se vacía.
Soy solo yo?, a alguién mas le pasa?, version 2.7.4 con woo 4.2.1 en php 7.3.14

**Comment by svaldesm** [comment]
@truchosky hola! yo lo acabo de probar para confirmar y no me pasa.
igual yo tengo productos usados, o sea es una unidad por c/u, pero de todas formas me debería pasar que se quedan en el carro y me dice que no hay stock. 
_creo_ que está correcto y mis clientas no han reportado nada.
saludos!

**Comment by gonzunigad** [comment]
Hola! Acabo de probar en un woocommerce nuevo y tampoco me pasa :)
Hay una configuración para definir en que estado quedan las ordenes cuando se finaliza un pedido, ¿cuál tienes configurada? @truchosky

**Comment by ffiebig** [comment]
@truchosky voy a cerrar este hilo, si tienes alguna novedad o quieres responder la pregunta de Gonzalo solo re abrelo

**Comment by truchosky** [comment]
hola @gonzunigad , quedan en procesando, al parecer es un problema con mi plugin de caché (wp rocket), lo raro es que con otros medios de pago no me sucede, así que seguiré haciendo pruebas

**Comment by svaldesm** [comment]
@truchosky yo tengo el mismo plugin y sí me resulta, no creo que sea eso.
eso si, debo decir que cuando las órdenes son muy grandes, se queda en procesando pero eventualmente pasa a completado, pero se demora (porque WP Rocket limpia el cache de cada producto). Estoy hablando de 10+ productos por orden.

Saludos!
