### ISSUE TITLE
Timeout conectando a WebPay, log muestra token duplicado, se descuenta a cliente

### ISSUE THREAD

**Issue by eperezf** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#134]
**Describe el bug**

Algunas órdenes pasan de exitosas a fallidas en WooCommerce después de que el pago haya sido realizado, cobrando al cliente pero dejando la orden como fallida.

**Para reproducir**

1. Realizar compra
2. Pagar
3. WebPay muestra transacción como exitosa
4. WooCommerce cambia el estado de Procesando a Fallido

**Comportamiento observado**

En WoCommerce, en el detalle del pedido se puede ver que la primera nota dice "Pago exitoso con WebPay Plus". En el log del plugin hay un getTransactionResult en la hora indicada. Sin embargo, 27 segundos después llega un segundo getTransactionResult idéntico, lo cual podría estar provocando el cambio de Procesando a Fallido. Se agrega una nueva nota al pedido que indica 

```
{
«error»: «Error conectando a Webpay (Verificar que la información del certificado sea correcta)»,
«detail»: » Timeout error(272) »
}
```
El certificado está correcto ya que otras transacciones sí funcionan.

En un caso llega incluso un tercer getTransactionResult pero con un token diferente. Al parecer ocurre un Timeout a Webpay cuando la transacción ya ha sido realizada. 

Según los clientes el que falla es WebPay pero no hemos podido verificarlo y por lo que muestra el log no lo es.

Este comportamiento parece ser aleatorio. No hemos encontrado algo en común entre transacciones que pueda ser la causa.

**Comportamiento esperado**

Siguiendo la lógica del resto del log, debería llegar solamente un getTransactionResult para cada transacción.

**Capturas de pantalla**

<img width="1824" alt="Captura de Pantalla 2020-06-27 a la(s) 12 39 17" src="https://user-images.githubusercontent.com/6854338/85927387-b83d5b00-b873-11ea-91a0-cb229378199f.png">
<img width="273" alt="Captura de Pantalla 2020-06-27 a la(s) 12 43 24" src="https://user-images.githubusercontent.com/6854338/85927431-005c7d80-b874-11ea-857f-e631102e7c25.png">

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 2.7.4
- Woocommerce: 3.9.1
- PHP: 7.1.33

**Comment by ffiebig** [comment]
Hola @eperezf gracias por reportarlo vamos a tener que revisar a fondo y con calma que está generando esto. Efectivamente solo debería hacer una llamada a `getTransactionResult`. Si llegas a encontrar una forma de consistentemente replicar el bug cuentanos porfa

**Comment by eperezf** [comment]
No he encontrado una forma consistente de replicarlo Parece ser aleatorio. Y tampoco hay una correlación entre clientes.

**Comment by gonzunigad** [comment]
Hola. Entiendo que esto ya no pasa en la última versión del plugin. Si tienen más info, volvemos a abrir el issue.
