### ISSUE TITLE
Wordpress Multisite Webpay

### ISSUE THREAD

**Issue by cecheverriam** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#138]
**Describe el bug**

Estimados,
Estoy usando la versión 3.2 de Woocommerce tal como aparece en los requerimientos.
Si bien el plugin funciona correctamente en el sitio principal de Wordpress, no logra activarse para los otros sitios del Wordpress multisite.

**Comportamiento observado**
El error aparece en la página de checkout donde no aparece la opción de comprar vía Webpay, sólo parecen los otros modos de pago.

**Capturas de pantalla**

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 2.7.5
- Woocommerce: 3.2
- PHP: 7.2.32

**Comment by gonzunigad** [comment]
Hola @cecheverriam . El plugin no tiene soporte oficial para sitios wordpress mutisite. Más que un bug, lo dejaré marcado como una solicitud de feature.

**Comment by gonzunigad** [comment]
Hola! Este plugin ya no recibirá mejoras. Puedes solicitar la mejora en el nuevo plugin REST: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest
