### ISSUE TITLE
Error Respuesta de Transbank

### ISSUE THREAD

**Issue by kevingayoso** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#139]
**Describe el bug**

Hola amigos, puse todo lo que se debe en la configuración de Transbank pero al hacer la compra de prueba para probar el servicio, no levanta el formulario. Revise en la configuración del plugin, en información del sistema y me dice que esta todo OK, cuando pincho en verificar conexión me dice error. Hable con Transbank e hice denuevo la llave y los certificados, ellos lo subieron nuevamente pero el error persiste.

Espero alguien me pueda ayudar, o si han pasado por el mismo problema, que han hecho??

Muchas gracias por su tiempo para leer.

![Captura de Pantalla 2020-07-17 a la(s) 19 51 32](https://user-images.githubusercontent.com/67850439/87839009-00461100-c867-11ea-990f-0dfee675272c.png)
![Captura de Pantalla 2020-07-17 a la(s) 19 51 35](https://user-images.githubusercontent.com/67850439/87839012-020fd480-c867-11ea-945e-157dbd8f10aa.png)

**Versiones:
- Plugin: [2.7.5]
- Woocommerce: [ej. 4.3]
- PHP: [ej. 7.3]

**Comment by truchosky** [comment]
a mi me paso una vez con el certificado también, yo lo generaba en linux con openssl (debian 10 si mal no recuerdo) y al parecer era incompatible, tuve que generarlo en windows con cmd, y pasó

**Comment by kevingayoso** [comment]
> a mi me paso una vez con el certificado también, yo lo generaba en linux con openssl (debian 10 si mal no recuerdo) y en mi mac, en ambos al parecer era incompatible, tuve que generarlo en windows con cmd, y pasó

Amigo finalmente lo pude solucionar con Transbank, resulta que el nombre del negocio tenia un símbolo que obstruía el certificado, por eso me daba error y no funcionaba.

Saludos!

**Comment by truchosky** [comment]
cual era el caractér?

**Comment by kevingayoso** [comment]
era "`"

**Comment by gonzunigad** [comment]
Hola @kevingayoso. ¿Pudiste solucionarlo?

**Comment by gonzunigad** [comment]
Puedes unirte a la comunidad de slack para darte soporte, no creo que sea un error del plugin, por lo que cerraré el issue. 
https://join-transbankdevelopers-slack.herokuapp.com/ háblanos por ahí.
