### ISSUE TITLE
Error plugins webpay woocommerce

### ISSUE THREAD

**Issue by cadagoze** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#140]
he configurado todo el ciclo de compra, permite ingresar la tarjeta y al momento de efecturar la transaccion muestra este error. 

Fatal error: Uncaught Transbank\WooCommerce\Webpay\Exceptions\TokenNotFoundOnDatabaseException: Token 'ed35e9f1a8e926ef03c0ece9171ca49848d1be6aedd927010cdf85fc979bd660' no se encontró en la base de datos de transacciones, por lo que no se puede completar el proceso in /home/amazingg/public_html/wp-content/plugins/woocommerce-transbank/src/TransbankWebpayOrders.php:40 Stack trace: #0 /home/amazingg/public_html/wp-content/plugins/woocommerce-transbank/src/Controllers/ResponseController.php(31): Transbank\WooCommerce\Webpay\TransbankWebpayOrders::getByToken('ed35e9f1a8e926e...') #1 /home/amazingg/public_html/wp-content/plugins/woocommerce-transbank/webpay.php(301): Transbank\WooCommerce\Webpay\Controllers\ResponseController->response(Array) #2 /home/amazingg/public_html/wp-includes/class-wp-hook.php(287): WC_Gateway_Transbank->check_ipn_response('') #3 /home/amazingg/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #4 /home/amazingg/public_html/wp-includes/plugin.php(478): WP_Hook->do_action in /home/amazingg/public_html/wp-content/plugins/woocommerce-transbank/src/TransbankWebpayOrders.php on line 40

**Comment by gonzunigad** [comment]
Hola @cadagoze ¿te pasa siempre con cada compra o en algunos casos en específico?
Ese error sucede cuando se llega a la página de response pero sin enviar el token de la transacción. Siempre que transbank hace la redirección lo hace enviando este token, por lo que el error se da si intentas ingresar directamente a la página, lo que no debe ser posible (por eso arrojamos ese error)

**Comment by cadagoze** [comment]
Buenas tardes Gonzalo, muchas gracias por responder, este mensaje de error solo aparece cuando esta realizando la finalizacion de la compra, he vaciado el carro de compra y vuelto a agregar el producto, de igual forma sigue apareciendo este error, seria muy amable en el poder guiarme u obtener documentación al respecto, muchas gracias y buenas tardes.

**Comment by gonzunigad** [comment]
@cadagoze, agredeceré me indiques de mejor forma que puedo hacer para replicar el error, idealmente paso por paso, para así poder resolver el error si es que efectivamente se trata de un bug. ¿Me ayudas con eso?

**Comment by ffiebig** [comment]
Cerramos por inactividad
