### ISSUE TITLE
Imagen muy grande

### ISSUE THREAD

**Issue by sterenas** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#145]
Buenos días, actualizé desde la versión 2.6.1 a la versión 2.7.7.  El changelog de la 2.7.0 indica que se areregla el tamaño de la imagen Transbank en la página de Finalizar pero en la versión 2.7.7 me sigue apareciendo enorme.  Persiste el problema?  Estamos usando las ultimas versiones de todos los plugins y Wordpress.
Mucho agradecería si pudieran hacer una prueba en https://moonwear.cl agregando un producto al carro y Finalizar Compra para ver el tamaño de la imagen.
Muchas gracias!

**Comment by juliohv-chile** [comment]
Hola, yo no se usar Github y ojala que responder no sea un problema, pero en mis comercios si se vio el cambio, visite tu tienda y la imagen se ve bien (150X18) , creo que es un tamaño aceptable:
https://moonwear.cl/wp-content/plugins/woocommerce-transbank/libwebpay/images/webpay.png
Si a ti se te aparece con otro tamaño debe ser algun cache, veo que no usas Cloudflare entonces podria ser local. Saludos.

**Comment by sterenas** [comment]
Muchas gracias Julio. Funcionó bien tu respuesta :) Entré a la página en modo incognito, efectivamente aparece pequeña. Muchas gracias por tu ayuda y tiempo, seguro es el cache. Cierro el issue. Gracias!
