### ISSUE TITLE
Pedidos con forma de Pago WebPay no disparan webhooks con status "processing" (v2.7.7)

### ISSUE THREAD

**Issue by davibertolini** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#146]
Buenas tardes, reportamos que se presenta la siguiente falla al momento de cambiar estatus de una orden Woocommerce durante el Flujo de Pago de la Orden con WebPay y la información que se dispara en los Webhooks.

## Antecedentes:

- Clientes con WebPay Plus modalidad NORMAL

- Se está usando la versión del plugin Wordpress 2.7.7 que es la última publicada en el sitio oficial de transbankdevelopers.cl y en el portal oficial de Transbank de GitHub

- Se está usando Wordpress Versión 5.5 (ultima oficial), Woocommerce Versión 4.4.1 (ultima oficial) sobre un servidor con NGINX y PHP 7.3.0

## Problema

Cuando se crea la orden en Woocommerce, se dispara el Webhook con el status "pending" pero este estatus, según la documentación, no garantiza que el pago se haya realizado correctamente, por lo que el sistema que recibe el webhook ignora estas cuentas.

![orderflow](https://user-images.githubusercontent.com/17347794/91090291-d54b9b80-e622-11ea-926a-2f4bd32486f1.png)

Luego, cuando la transacción se confirma como Pagada con WebPay Woocommerce dispara una o más llamadas hacia el sistema que recibe los Webhooks, al menos uno de ellos se asume que debe venir con el status "processing" ya que según la documentación Woocommerce este es el estatus que se considera como “aceptado” (es decir que la transacción y forma de pago fueron aceptados). Solo las llamadas de Woocommerce que llegan al sistema que recibe los Webhooks con el estatus processing son las que Novohit utiliza para crear cuenta.

Las ordenes pagadas con WebPay nunca están llegando al sistema  con el estatus processing, todas las otras formas de pago si.

Esto parece que fue reportado en el Pull #141 y en el [Fix 2.7.6](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/releases/tag/2.7.6), pero como indicado en los antecedentes tenemos instalado el 2.7.7 y el problema persiste. 

En este momento tenemos deshabilitado el plugin ya se están recibiendo cientos de ordenes al día y el pago genera incertidumbre ya que el sistema que recibe los webhooks es el sistema central ERP que procesa las ordenes de trabajo.

Quedamos atentos a sus comentarios. Gracias de antemano.

**Comment by TBMSP** [comment]
Yo llame a soporte de transbank, y me dijeron que era el tema de las cookies, por una actualización de Google Chrome "SameSite=None" lo intente revisar y hacer los cambios en la plataforma, pero sigo igual, no se si estoy haciendo algo mal o algo así, pero esa es la respuesta que me dieron, igual sigo investigando el samesite pero te lo dejo en caso de que puedas solucionarlo hasta encontrar alguna solución

**Comment by truchosky** [comment]
revisaste en el log si fueron enviados?, yo también utilizo webhooks (solo los que van con estado processing) y no he tenido ningun problema, version 2.7.6 transbank , php 7.4.9 y nginx, woocomerce y wordpress a la última version

**Comment by davibertolini** [comment]
@truchosky Si, Los logs de woocommerce fueron revisados y los webhook no se disparan. Las órdenes quedan con el status "Processing", pero ese WebHook no se dispara hacia al sistema. Recibimos decenas y aveces centenas de órdenes durante los fines de semana y se presentó solo en algunas órdenes. ¿ en su infraestructura ustedes tienen algún sistema de caching?

@TBMSP No revisé las ordenes que tuvieron este problema si fueron realizadas con Chrome.

**Comment by truchosky** [comment]
redis

**Comment by ffiebig** [comment]
@truchosky ojo que los productos digitales no deberían caer en processing sino que en Completed

**Comment by truchosky** [comment]
@ffiebig la verdad no creo, ningún plugin de pago (webpay, khipu, flow, payku, etc) deja los pedidos de los productos "virtuales" en completado, porque debería quedar en completado?, si ese fuera el caso no tendría sentido usar webhooks, nosotros usamos esa herramienta justamente para "procesar" los pedidos, una vez procesado en e l ssitema externo de woocomerce se marca como completado (directamente en éste con la api de woocomerce)

**Comment by gonzunigad** [comment]
Hola! Este plugin ya no recibirá mejoras, por lo que recomendamos cambiarse al plugin REST: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest

**Comment by davibertolini** [comment]
> Hola! Este plugin ya no recibirá mejoras, por lo que recomendamos cambiarse al plugin REST: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest

@gonzunigad el nuevo Plugin requiere un API Key (ya no solicita los certificados o llave privada como el plugin anterior), sin embargo no está documentado de dónde se obtiene el API Key. 

Uno podría asumir que el API Key se descarga desde el Portal Servicios https://www.transbank.cl/portal-servicios/ sección WebPay pero no sale allí, además el portal servicios arroja error (desde cualquier navegador).

![Screen Shot 2020-12-03 at 16 43 19](https://user-images.githubusercontent.com/17347794/101079996-fb1fff00-3586-11eb-96f8-4f969c657d22.jpg)

**Comment by truchosky** [comment]
x 2, donde está la api key?

**Comment by gonzunigad** [comment]
Hola! Acá esta la doc: https://transbankdevelopers.cl/documentacion/como_empezar#obtener-tu-llave-secreta-proceso-de-validacion

La envía soporte@transbank.cl una vez que envían el documento de validación. Ya no hay certificados que generar ni nada, solo vuelvan a enviar el documento de validación (el de REST) y en 24 horas deberían enviarles su api key :)
