### ISSUE TITLE
al finalizar compra no arroja voucher transbank wc-api=WC_Gateway_transbank

### ISSUE THREAD

**Issue by Nikitogo** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#148]
buenas tarde estimados!
una vez realizado el pago la pantalla queda en blanco no arrojando el voucher de transbank por lo cual menos redirecciona a la página web
el dinero es descontado y en panel admin aparece que el pago fue existoso 

**Capturas de pantalla**
![gggggg](https://user-images.githubusercontent.com/68706066/91759297-6da3cc00-eb9f-11ea-918b-2d5640df4835.PNG)

Si aplica, agrega aquí capturas de pantalla que ayuden a explicar tu problema.

**Versiones :**
- Plugin: [2.7.7]
- Woocommerce: [4.4.1]
- PHP: [7.4.8]

**Contexto adicional**

Agrega cualquier otro información sobre el problema aquí.

**Comment by afiebig** [comment]
Hola @Nikitogo este error se presenta desde cuando?

**Comment by Nikitogo** [comment]
se presenta hace un par de días a veces arroja el voucher y otras no 
por ejemplo he realizado mas de 4 pruebas y todas se van a pantalla blanca 
hace dias sucedio lo mismo pero en unas cuentas si arrojo voucher

**Comment by afiebig** [comment]
Veo que estas usando Chrome, puedes realizar una prueba en un navegador diferente? de preferencia firefox. Gracias

**Comment by Nikitogo** [comment]
**actualizacion**
 hice una prueba desde otro pc con navegador firefox y si arroja voucher

**Comment by afiebig** [comment]
Probablemente este relacionado entonces con la actualización de chrome 80. Puedes verificar que las cookies que estas enviando esten marcadas como SameSite=None y Secure.

**Comment by Nikitogo** [comment]
me dices donde encuentro esta informacion por favor

**Comment by Nikitogo** [comment]
se puede hacer algo para solucionar este incidente
?

**Comment by afiebig** [comment]
Si efectivamente el problema esta relacionado con las Cookies, entonces no es parte del plugin, sino de tu e-commerce. ya que este plugin no utiliza sesiones para terminar el pago.

**Comment by Nikitogo** [comment]
entiendo alguna posible solución? o donde pueda orientarme para solucionar esto

**Comment by Nikitogo** [comment]
Estimado alguna solucion de donde revissar o asignar estas cookies?

**Comment by TBMSP** [comment]
Intenta con esto en el archivo llamado ".htaccess"

Header always edit Set-Cookie (.*) "$1; SameSite=None; Secure"

Tienes que colocar ese codigo al principio o al final, este convierte tus cookies a samesite none y secure como lo solicita pero nosé si te funcione, el htaccess lo encuentras en la carpeta public_html principal de tu servidor (puedes entrar via ftp) o tambien con el administrador de archivos de cpanel si es que lo tienes

**Comment by gonzunigad** [comment]
Hola! este problema está resuelto en las últimas versiones del plugin. Pueden cambiarse al plugin REST acá: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest
