### ISSUE TITLE
Transacciones de Débito Reversadas

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#149]
Estimados,

De vez en cuando obtenemos transacciones con Débito reversadas. Entiendo que este problema se debe a problemas de comunicación entre Transbank y el Comercio.
¿Qué consejos pueden dar para evitar que este tipo de errores ocurran en el futuro?

Plugin actualizado
Woocommece 4.3.3
Wordpress: 4.9.1
Cloudflare+ WP Rocket y SG Optimizer

**Comment by afiebig** [comment]
Hola, este error puede producirce por multiples problemas, entre ellos red u otros, no esta relacionado con el plugin. Si tienes algún caso especifico te invito a la comunidad de Slack para realizar este tipo de consultas: https://join-transbankdevelopers-slack.herokuapp.com/
