### ISSUE TITLE
Error de conexión

### ISSUE THREAD

**Issue by gaborecondo21** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#151]
Hola amigos, al Validación transacción mediante pluging de wooocomerce me arroja este error:

No se ha creado la transacción para, amount: 990, sessionId: 5f5f992b9cd2e, buyOrder: _Healthcheck_

**Comment by afiebig** [comment]
Hola @gaborecondo21 te invito a realizar estas preguntas en nuestro slack de integradores: https://join-transbankdevelopers-slack.herokuapp.com/
