### ISSUE TITLE
Resultado transaccion

### ISSUE THREAD

**Issue by guzmanf** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#155]
Estoy haciendo pruebas y no logro obtener la informacion de resultado de la transaccion devuelta por transbank al ejecutar la siguiente instruccion
$resultadoTBK = WC()->session->get( $order->get_order_key() );

o se obtiene de otro la informacion ?

salu2

**Comment by ffiebig** [comment]
Hola, probablemente es por las cookies samesite, chrome las borra y se pierde la sesión

**Comment by gonzunigad** [comment]
Hola, esa información la puedes obtener de la tabla webpay_transactions. 👍 
PD: Es importante que te cambies a el nuevo plugin REST: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest
