### ISSUE TITLE
No se recibe el detalle de pago en los pedidos nuevos

### ISSUE THREAD

**Issue by ExD4t4** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#158]
Buenas Muchachos:

No tengo idea de si puedo hacer esta consulta aquí pero espero que puedan orientarme un poco al respecto:

Resulta que cuando el cliente paga con tarjeta de forma exitosa, yo al ver el detalle del pedido, aparte de los artículos que compra el cliente, debajo me muestra unos campos personalizados donde van los datos de la tarjeta como son, el código de autorización, el numero de tarjeta, las cuotas (si es con tarjeta de crédito), el monto y el tipo de tarjeta (visa, mastercard, etc)
de esta manera:
https://ibb.co/D5NwGsr

sin embargo, ahora los muestra así:
https://ibb.co/8MDbdhV

como pueden ver, no trae los datos del pago. Y estos datos son importantes pues van a los campos de datos de Softland para emitir la boleta electrónica.
al consultarlo con woocommerce me dijeron que esos datos los aporta el plugin de pago, en este caso transbank. Antes obviamente funcionaba bien, ahora no se a que se deba el error o donde deba empezar a buscar.

Pueden orientarme un poco con eso? o a alguien mas le sucede?

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: Transbank Webpay Plus [Versión 2.6.1]
- Woocommerce: [Versión 4.6.2]
- PHP: [7.4]
-Wordpress: [5.4.4]

**Comment by jprush76** [comment]
Hola @ExD4t4 , yo no trabajo en transbank, pero la falta de información en los campos personalizados pasa sólo en los pedidos que el pago es aceptado en una segunda instancia? o para todos los pedidos??

Saludos.

**Comment by ExD4t4** [comment]
> Hola @ExD4t4 , yo no trabajo en transbank, pero la falta de información en los campos personalizados pasa sólo en los pedidos que el pago es aceptado en una segunda instancia? o para todos los pedidos??
> 
> Saludos.

Hola, solo para los pedidos aceptados (que efectivamente Transbank acepta) pues los demás pedidos (los fallidos) no se necesita esa info y no debería entregar el código de autorización ni nada más 
Saludos

**Comment by gonzunigad** [comment]
Hola! Este problema está resuelto. Les recomendamos cambiarse al nuevo plugin REST: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest
