### ISSUE TITLE
Error al mostrar comprobante de pago (Transbank Webpay Plus REST)

### ISSUE THREAD

**Issue by zeiz72** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#159]
Estimados,

Al momento de mostrar el comprobante de pago muestra esta ventana con error, antes no ocurría:

https://apoyando.me/?wc-api=WC_Gateway_transbank_webpay_plus_rest

Pantalla con error
![Screenshot_108](https://user-images.githubusercontent.com/74872102/99910973-1578f380-2cd0-11eb-9371-812fc9a5b8b2.png)

Versiones.
![Screenshot_109](https://user-images.githubusercontent.com/74872102/99910974-1873e400-2cd0-11eb-9e81-8d6a7b189f17.png)

Saludos,
Zeiz72

**Comment by gonzunigad** [comment]
Hola @zeiz72 . Necesitamos los logs del servidor para saber que pasó. Tu Wordpress tiene desahbilitado mostrar los erroes, por lo que en el pantallazo solo vemos que hay un error, peor no sabemos que error.

**Comment by gonzunigad** [comment]
Hola! también te comento que este issue está en el repositorio del plugin SOAP. Ideal si publicas este issue en https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest

**Comment by Moriort** [comment]
Mismo problema WooCommerce última versión 6.2.1, Wordpress 5.9.1
