### ISSUE TITLE
Problema procesando transaccion

### ISSUE THREAD

**Issue by lmatab** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#16]
Tengo una instalacion nueva de woocommerce , servidor con php 7.1, mysql , y cloudflare.

En la ultima etapa de la verificación del pago no se logra procesar y me arroja  Error 504.

https://site.cl/?wc-api=WC_Gateway_transbank&orid=11

**Comment by leosoto** [comment]
@lmatab ¿Fue un problema que ocurrió en Enero y se ha resuelto? ¿O sigues observando el mismo problema?

**Comment by sonda123** [comment]
Yo tuve muchos problemas con cloudflare.

**Comment by truchosky** [comment]
creo que deben poner en la "lista blanca" de cloudflare la IP o IPs de transbank

**Comment by a1b4** [comment]
Hola, daré por cerrado este issue debido a que no se ha obtenido confirmación de que el problema persista. 

Saludos.!
