### ISSUE TITLE
Notificación Actualización Transbank de SOAP a REST

### ISSUE THREAD

**Issue by jprush76** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#160]
Hola equipo de Transbank, espero que se encuentren muy bien, me acaba de llegar un correo indicando que transbank webpay comienza a operar con una solución REST y que en el mediano plazo, SOAP (JUL 2022) dejará de funcionar. Que implicancias tiene este cambio para las empresas que utilizamos el plugin woocommerce de transbank?
Ojalá me puedan ayudar con esta duda.

Saludos,

Jaime

**Comment by gonzunigad** [comment]
Hola! el nuevo plugin es básicamente lo mismo, pero usando el API REST. 
Debes enviar [este formulario](https://transbankdevelopers.cl/files/evidencia-integracion-webpay-plugins-rest.docx) a soporte@transbank.cl y ellos te enviarán un API Key (llave secreta). Con esa llave secreta, ya podrás cambiarte de plugin SOAP a REST. 

Eliminr el plugin SOAP, baja e instala el [nuevo plugin REST](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest) y verás que ya no te pide certificados, solo tu código de comercio y el API Key que te entregaron tras validar tu nuevo formulario (el que envías a soporte).
