### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by maximoarancibia** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#18]
Estimados:

Buenas tardes no me es posible activar el plugin :  

Woocomerce me dice la siguiente respuesta en la vista!

Fatal error: require_once(): Failed opening required '/wordpress/core/5.0.3/wp-content/plugins/woocommerce-transbank/vendor/autoload.php' (include_path='/:.') in /srv/htdocs/wp-content/plugins/woocommerce-transbank/webpay.php on line 26

**Comment by arkive** [comment]
Tenemos exactamente el mismo problema:

Warning: require_once(/home/arkive/public_html/test/wp-content/plugins/woocommerce-transbank/vendor/autoload.php): failed to open stream: No such file or directory in /home/arkive/public_html/test/wp-content/plugins/woocommerce-transbank/webpay.php on line 26

**Comment by CLobo96** [comment]
Hola! Para quienes aun se encuentran este problema, el motivo es que el plugin ha sido subido con un nombre distinto a woocommerce-transbank por tanto la ruta no se encuentra. Recomiendo entrar por FTP a su directorio wordpress, entrar a /wp-content/plugins y crear el directorio woocommerce-transbank. En este directorio vaciar los contenidos del zip, quedando webpay.php en la direccion /wp-content/plugins/woocommerce-transbank/webpay.php . Posteriormente activar el plugin desde el panel de wordpress.


Saludos

**Comment by goncafa** [comment]
Hemos creado un issue en Jira para atender este tema según disponibilidad: https://transbank-developers.atlassian.net/browse/TD-278

**Comment by ffiebig** [comment]
Hola, @maximoarancibia, @arkive, @CLobo96 que versión de PHP utilizaron ?

**Comment by a1b4** [comment]
Hola a todos, hemos resuelto este problema en la [última versión publicada del plugin ](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/releases/tag/2.2.4.) 🎉 🎉
