### ISSUE TITLE
El plugins no completa el proceso de redireccionamiento a pago

### ISSUE THREAD

**Issue by UpperCod** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#19]
Junto con saludarlos adjunto detalle del error generado por php al ejecutar el constructor SOAP, en el proceso de apertura de transacción de transbank.

Error generado : 

```
Fatal error: Uncaught SoapFault exception: [Client] SoapClient::SoapClient(): 'uri' option is required in nonWSDL mode in /home/studiomu/public_html/tienda/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php:16 Stack trace: #0 /home/studiomu/public_html/tienda/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php(16): SoapClient->SoapClient(NULL, Array) #1 /home/studiomu/public_html/tienda/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/WebPayNormal.php(66): Transbank\Webpay\WSSecuritySoapClient->__construct(NULL, '-----BEGIN RSA ...', '-----BEGIN CERT...', Array) #2 /home/studiomu/public_html/tienda/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/Webpay.php(74): Transbank\Webpay\WebPayNormal->__construct(Object(Transbank\Webpay\Configuration)) #3 /home/studiomu/public_html/tienda/wp-content/plugins/woocommerce-transbank/libwebpay/Tran in /home/studiomu/public_html/tienda/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php on line 16
```

Revise el error y al ver los argumentos enviados  a la clase `WSSecuritySoapClient`, note que se genera un error en la obtención de la url para el constructor, line 63 fichero WebPayNormal.php, este obtiene mediante la variable `$mode` el índice de la url a utilizar, el problema es simple wordpress envía el nombre en inglés `INTEGRATION` y el arreglo posee el nombre en español `INTEGRACION`, esto genera que la URL recibida sea NULL. 

Espero que este sea un problema único frente al uso del plugins, yo puedo solucionarlo manipulando el código pero esperare que lancen una versión que evite este bug

**Comment by reandimo** [comment]
Tuve el mismo problema, gracias por el dato para corregirlo!

**Comment by UpperCod** [comment]
@reandimo, Transbank posee un slack de desarrolladores, te invito a ingresar a [transbankdevelopers.slack.com](https://transbankdevelopers.slack.com)  hay discuti el error, la solución es la siguiente, copio la conversación 

*efectivamente hay un error en el nombre del ambiente, que difiere con el nombre que espera el SDK PHP embebido en el plugin.  Queda con nombre `INTEGRATION` guardado en la base de datos cuando se instala el plugin, pero el seleccionador de ambientes lo tiene bien escrito, `INTEGRACION`.  Al hacer la solución temporal, fuerza a que se guarde en base de datos con el nombre correcto.*

espero que te sea de utilidad

**Comment by leosoto** [comment]
Fixed in #20 and released in v2.1.6.

@UpperCod @reandimo: Lo ideal es que se actualicén a versión 2.1.6 o superior.

**Comment by exsonreyes** [comment]
yo tengo este problema y no se que pasa no puedo entrar al WordPress. Warning: session_start(): Failed to read session data: files (path: /var/cpanel/php/sessions/ea-php71) in /home/sfachile/public_html/wp-content/plugins/transbank-webpay-plus-rest/webpay-rest.php on line 82

Warning: Cannot modify header information - headers already sent by (output started at /home/sfachile/public_html/wp-content/plugins/transbank-webpay-plus-rest/webpay-rest.php:82) in /home/sfachile/public_html/wp-includes/pluggable.php on line 1355

Warning: Cannot modify header information - headers already sent by (output started at /home/sfachile/public_html/wp-content/plugins/transbank-webpay-plus-rest/webpay-rest.php:82) in /home/sfachile/public_html/wp-includes/pluggable.php on line 1358
