### ISSUE TITLE
Error con el nombre de Carpeta subido.

### ISSUE THREAD

**Issue by benjaspencer** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#24]
La carpeta que se installa termina con el numero de versión 2.2.0 y en PHP llama a la carpeta sin versión dando error.

<img width="676" alt="captura de pantalla 2019-03-04 a la s 19 08 34" src="https://user-images.githubusercontent.com/7224711/53767401-720cfd00-3eb4-11e9-98fd-9e9035c073d5.png">
![captura de pantalla 2019-03-04 a la s 19 08 42](https://user-images.githubusercontent.com/7224711/53767623-198a2f80-3eb5-11e9-8094-128648f5d7dc.png)

**Comment by goncafa** [comment]
Gracias por tu reporte

Issue creado en Jira para ser atendido según disponibilidad: https://transbank-developers.atlassian.net/browse/TD-277

**Comment by ffiebig** [comment]
@benjaspencer no hemos podido replicar el problema descargando el plugin e instalandolo.

Lo que si logramos ver es que es si el archivo es renombrado cambia el nombre de la carpeta que se crea dentro de `wp-content/plugins`.
 
Nos serviría mucho que nos puedas dar más información. ¿Nos puedes contar, paso a paso, qué hiciste cuando te encontraste con esto?

De nuevo, gracias por el reporte

**Comment by benjaspencer** [comment]
El error visto fue que al descargar el archivo del plugin, venía la carpeta con el nombre 2.2.1 pero en el código no llamaba al plugin con nombre en carpeta 2.1.1 generando problema.
No estoy seguro si habrá sido un problema de una versión específica mal subida de su parte o de mi parte pero lo bueno es que está corregido, mil gracias!

**Comment by ffiebig** [comment]
Dado que no pudimos replicar el problema y al parecer es una causa externa cerramos el issue. De todas maneras, si alguien más se ve afectado por el problema le pedimos que nos deje el paso a paso para que podamos replicarlo. Idealmente en un nuevo issue.
