### ISSUE TITLE
Función obsoleta - No reduce el stock

### ISSUE THREAD

**Issue by janovoas** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#25]
Estimados, existe al menos una función de WooCommerce obsoleta en el plugin.
La alerta salta al realizar una compra exitosa y reducir el stock desde la orden:

`PHP Notice:  WC_Order::reduce_order_stock ha quedado <strong>obsoleto</strong> desde la versión 3.0. Utiliza wc_reduce_stock_levels en su lugar.`

Por lo tanto, la línea **228** de webpay.php, debería reemplazarse por:
`wc_reduce_stock_levels($order_id);`

Me parece que es un ajuste urgente, ya que **no permite reducir el stock del producto**.

Recién descargué esta versión del plugin, por lo que no he podido revisar si existen más, aunque al parecer no las hay (al menos al procesar un pago exitoso desde tarjeta de débito).

https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/blob/92200ab09ad891293a64bd6d8f4259be2790344a/woocommerce-transbank/webpay.php#L228

**Comment by goncafa** [comment]
Hola @janovoas el problema esta corregido en la versión 2.2.1 del plugin. Muchas gracias!
