### ISSUE TITLE
Al tratar de completar la transacción no lo logra

### ISSUE THREAD

**Issue by ricardor1267** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#26]
Al tratar de finalizar la compra queda en https://www.misitio.cl/finalizar-comprar/order-pay/8498/?key=XXXXX no me avanza a la pagina de Webpay

Segun el modulo de herramientas del plugin me sale todo ok pero cuando trato de hacer la Petición a Transbank clickeando en el botón Verificar Conexion este queda en "Verficando" y no responde.

Php 5.6.40 

openssl | OK | OpenSSL  0.9.8e-fips-rhel5 01 Jul 2008
SimpleXml | OK | 0.1
soap | OK | PHP Extension Compiled. ver:5.6.40
dom | OK | 20031129

Cualquier Ayuda se agradece

**Comment by goncafa** [comment]
Consulta, revisaste este anuncio que se dio el Sábado en el canal de slack?

```
Hola! Durante este fin de semana (sábado 9 y domingo 10), el ambiente de integración de Webpay no estará disponible debido a una actividad programada.
```

Será que tiene relación con esto? podrías volver a intentar la transacción?

**Comment by ricardor1267** [comment]
Active el debug y veo este error

Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl' : failed to load external entity "https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl" in /home/ricardor/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php:16 Stack trace: #0 /home/ricardor/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php(16): SoapClient->SoapClient('https://webpay3...', Array) #1 /home/ricardor/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/WebPayNormal.php(69): Transbank\Webpay\WSSecuritySoapClient->__construct('https://webpay3...', '-----BEGIN RSA ...', '-----BEGIN CERT...', Array) #2 /home/ricardor/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/Webpay.php(74): T in /home/ricardor/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php on line 16

**Comment by goncafa** [comment]
Que pasa si intentas acceder al WSDL desde tu navegador? Yo al menos ahora mismo pude accederlo sin problema. Es posible que tu servidor no tenga acceso a él por alguna razón.
@ricardor1267

**Comment by ricardor1267** [comment]
Estoy consultado a la empresa de hosting para verificar algún bloqueo o falta de libreria

**Comment by goncafa** [comment]
Dado que este error apunta a que el error esta en la comunicación entre el servidor con el endpoint de transbank (puede ser por bloqueos en la maquina) y no con un error del SDK es que lo dejare cerrado. Si este alguien tiene un error similar y tiene como replicar los pasos para que el error se presente en cualquier maquina y se descarte un problema de bloqueos externos puede abrir un nuevo issue y presentar los detalles.

**Comment by smithplus** [comment]
Hola, estoy teniendo exactamente este mismo problema con dos webs. 
He confirmado y tengo habilitado SOAP en mi hosting.

`Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl' : failed to load external entity "https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl" in /home/u888237244/domains/scaichile.cl/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php:16 Stack trace: #0 /home/u888237244/domains/scaichile.cl/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php(16): SoapClient->SoapClient('https://webpay3...', Array) #1 /home/u888237244/domains/scaichile.cl/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/WebPayNormal.php(66): Transbank\Webpay\WSSecuritySoapClient->__construct('https://webpay3...', '-----BEGIN RSA ...', '-----BEGIN CERT...', Array) #2 /home/u888237244/domains/scaichile.cl/public_html/wp-conte in /home/u888237244/domains/scaichile.cl/public_html/wp-content/plugins/woocommerce-transbank/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php on line 16`


[report_webpay_1590915226.pdf](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/files/4707513/report_webpay_1590915226.pdf)

**Comment by ronn835** [comment]
Hola tuve el mismo problema recien en un sitio web intentando integrar transbank con woocommerce,

Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl' : failed to load external entity "https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl" in /var/www/wp-content/plugins/woocommerce-transbank1/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php:16 Stack trace: #0 /var/www/wp-content/plugins/woocommerce-transbank1/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php(16): SoapClient->SoapClient('https://webpay3...', Array) #1 /var/www/wp-content/plugins/woocommerce-transbank1/vendor/transbank/transbank-sdk/lib/webpay/WebPayNormal.php(66): Transbank\Webpay\WSSecuritySoapClient->__construct('https://webpay3...', '-----BEGIN RSA ...', '-----BEGIN CERT...', Array) #2 /var/www/wp-content/plugins/woocommerce-transbank1/vendor/transbank/transbank-sdk/lib/webpay/Webpay.php(79): Transbank\Webpay\WebPayNormal->__construct(Object(Transbank\Webpay\Co in /var/www/wp-content/plugins/woocommerce-transbank1/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php on line 16

Alguna sugerencia para resolverlo ?

**Comment by jprush76** [comment]
> Hola tuve el mismo problema recien en un sitio web intentando integrar transbank con woocommerce,
> 
> Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl' : failed to load external entity "https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl" in /var/www/wp-content/plugins/woocommerce-transbank1/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php:16 Stack trace: #0 /var/www/wp-content/plugins/woocommerce-transbank1/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php(16): SoapClient->SoapClient('https://webpay3...', Array) #1 /var/www/wp-content/plugins/woocommerce-transbank1/vendor/transbank/transbank-sdk/lib/webpay/WebPayNormal.php(66): Transbank\Webpay\WSSecuritySoapClient->__construct('https://webpay3...', '-----BEGIN RSA ...', '-----BEGIN CERT...', Array) #2 /var/www/wp-content/plugins/woocommerce-transbank1/vendor/transbank/transbank-sdk/lib/webpay/Webpay.php(79): Transbank\Webpay\WebPayNormal->__construct(Object(Transbank\Webpay\Co in /var/www/wp-content/plugins/woocommerce-transbank1/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php on line 16
> 
> Alguna sugerencia para resolverlo ?

Hola @ronn835  tienes activado el módulo soap en php??

**Comment by ronn835** [comment]
Hola amigo, si, el modulo está activado!

**Comment by Cristobalius** [comment]
Tengo el mismo problema, tengo soap activado
