### ISSUE TITLE
Orden queda como "Procesando" y no como "Completada"

### ISSUE THREAD

**Issue by janovoas** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#27]
Estimados,
al momento de realizar el pago, la orden está quedando como "procesando" y no como "completada". Esto tiene algún fin, o es solo un error? Me parece que lo mejor es dejarla como completada, ya que el pago en este punto se realizó con éxito.

https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/blob/92200ab09ad891293a64bd6d8f4259be2790344a/woocommerce-transbank/webpay.php#L227

**Comment by melvinvita** [comment]
> Estimados,
> al momento de realizar el pago, la orden está quedando como "procesando" y no como "completada". Esto tiene algún fin, o es solo un error? Me parece que lo mejor es dejarla como completada, ya que el pago en este punto se realizó con éxito.
> 
> [transbank-plugin-woocommerce-webpay/woocommerce-transbank/webpay.php](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/blob/92200ab09ad891293a64bd6d8f4259be2790344a/woocommerce-transbank/webpay.php#L227)
> 
> Line 227 in [92200ab](/TransbankDevelopers/transbank-plugin-woocommerce-webpay/commit/92200ab09ad891293a64bd6d8f4259be2790344a)
> 
>                      $order_info->update_status('processing');

Creo que el proceso correcto es pasar por "Procesando", así funciona la mayoría o totalidad de pasarelas de pago, esto para dar un margen de tiempo para "preparación" del pedido.

**Comment by RodrigoAyala** [comment]
Hola @janovoas!, como dice @melvinvita es correcto que quede en estado "Procesando". 

Este flujo lo obtuve desde la documentación oficial de WooCommerce (https://docs.woocommerce.com/document/managing-orders/):
![Flujo de pago](https://user-images.githubusercontent.com/518591/54203853-cc5c1e00-44b1-11e9-8d3a-4b3c4c5f96ce.png)

El estado "Processing", significa que el pago se ha completado exitósamente y que se está procesando el producto para ser enviado al cliente.

**Comment by janovoas** [comment]
Algunos clientes me han preguntado por qué no pasa directo a "Completado", pero en realidad tiene lógica como lo planteas.
Gracias1
