### ISSUE TITLE
Cargo por porcentaje no se esta aplicando

### ISSUE THREAD

**Issue by returnvoid** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#34]
Hola

Al instalar version 2.2.1 con Woocommerce 3.5.7 en WordPress 4.7.3  no se esta aplicando "Cargo por porcentaje". Esto sucedio al actualizar a esta version
Tengo solo activado "Incluye impuestos en el cálculo".  
gracias

**Comment by a1b4** [comment]
@returnvoid hola, has podido solucionar este tema? si no lo has solucionado podrías darnos mayor antecedentes para poder replicar el error?

saludos.

**Comment by a1b4** [comment]
@returnvoid vamos a cerrar este issue ya que no hemos obtenido respuesta y tampoco han llegado otros reportes sobre lo mismo. En caso de que el problema persiste pueden escribir para re-abrir este issue

Saludos.
