### ISSUE TITLE
Transacciones fallidas

### ISSUE THREAD

**Issue by melvinvita** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#35]
Hola, hace poco he estado viendo un incremento considerable en los pedidos "Fallidos", se que esto puede deberse a varias razones ligadas al saldo de la cuenta o límites de tarjetas, pero he visto que pedidos ya con estado "procesando" y "completados" (o sea ya con pagos correctos y abonados) pasan a actualizarse a "Fallido" después de varios días de haberse completado, es un comportamiento extraño ya que en esos pedidos ya estaba todo el proceso terminado.

¿Es posible que esté ligado al plugin, o será algo de transbank como tal?

Usando: 
WordPress
WooCommerce 3.5.7
Webpay WooCommerce 2.2.1

Adjunto screenshot donde se puede ver que dos días después de haberse generado el pedido y el pago correctamente, se cambia a fallido

Saludos y muchas gracias.

![screenshot-camillaschile cl-2019 04 09-10-06-06](https://user-images.githubusercontent.com/47744981/55806954-4aaae080-5aaf-11e9-9069-c5c1840a49f9.png)

**Comment by ricardogonzalezcari** [comment]
Me sumo a @melvinvita
Mi cliente ha tenido exactamente los mismo problemas que mencionan.

Pedido fallidos a los cuales se descuentan los fondos a los clientes.
Para verificar ingresamos al portal de TBK y los pedidos como fallidos aparecen correctamente procesados.

Usando:
WordPress ultima versión
WooCommerce 3.5.7
Webpay WooCommerce 2.2.1
PHP 7.1

**Comment by melvinvita** [comment]
Han aumentado aún más, con incluso más días de diferencia.

Ahora usando:
WP 5.1.1
WC 3.5.7
Transbank 2.2.2
PHP 7.0.33

**Comment by ffiebig** [comment]
Hola @melvinvita creamos un ticket en Jira para revisar lo que reportas, te tendremos noticias lo más pronto posible

**Comment by melvinvita** [comment]
Hola @ffiebig, excelente, muchas gracias. Quedo atento.

**Comment by sonda123** [comment]
También con problema similar: 

![Screen Shot 2019-04-18 at 19 26 37](https://user-images.githubusercontent.com/47185145/56397058-fa9aef00-620f-11e9-9b6d-81447a00e581.jpg)
![Screen Shot 2019-04-18 at 19 26 52](https://user-images.githubusercontent.com/47185145/56397059-fa9aef00-620f-11e9-97c3-40dc9aecfc05.jpg)

**Comment by jprush76** [comment]
Hola @ffiebig  me sumo al problema de @melvinvita tenemos el mismo problema.. las transacciones son aceptadas y el pedido pasa a estado "procesando", pero a los 3 minutos cambian de estado a "fallido".
Esto se ha presentado en aprox el 10% de las transacciones, el resto de las compras son pagadas de forma normal.
Al revisar en la planilla de transbank, las transacciones aparecen como aprobadas.

Las transacciones con problemas tiran uno de los siguientes errores a los minutos de aprobadas:

{“error”:”Error conectando a Webpay (Verificar que la información del certificado sea correcta)”,”detail”:” Timeout error(272) “}

{“error”:”Error al confirmar la transacciu00f3n”,”detail”:”El token webpay es requerido”}

¿Habrá algún tipo de solución? El problema comenzó a presentarse a mediados de marzo, cuando actualizamos el plugin de woocommerce a la versión 2.2.1

Nuestra configuración:
woocommerce: 3.5.7
plugin transbank: 2.2.1
versión PHP: 7.0.33

Les dejo pantallazo del error más crítico... se procesó como exitoso, esta confirmado con cod de autorización de la transacción, lo procesamos, enviamos el pedido y a los 3 días se reversó solo el estado a "fallido".

Ojalá nos puedan ayudar con este problema.

Saludos, Jaime

![error transaccion piamaria](https://user-images.githubusercontent.com/17952983/56532621-1958f880-6524-11e9-83fc-93929d427a76.png)

**Comment by a1b4** [comment]
@melvinvita hola, estamos trabajando en este issue y tengo la siguiente consulta, has notado algún patrón relacionado a las transacciones que pasan a fallidas? el estado solo se modifica en woocommerce, o sea, en transbank siguen apareciendo como abonadas?

**Comment by melvinvita** [comment]
> @melvinvita hola, estamos trabajando en este issue y tengo la siguiente consulta, has notado algún patrón relacionado a las transacciones que pasan a fallidas? el estado solo se modifica en woocommerce, o sea, en transbank siguen apareciendo como abonadas?

Hola, @a1b4.

No he notado ningún patrón, el status solo se modifica en woocommerce, en Transbank quedan abonadas sin problemas. Pensé que podría ser un problema con el IPN, pero la verdad no estoy seguro.

Off topic: Por otro lado he visto muchas transacciones fallidas con distintos códigos de error, en la documentación aparece información sobre estos errores pero muy pobre. No se explica bien que ocasiona esos errores, por ejemplo los -1, -2 y -3. ¿De casualidad tienes un poco más de info al respecto?

Saludos y gracias de antemano.

**Comment by a1b4** [comment]
Hola, hemos solucionado el cambio de estado de transacciones en estados distintos a pendientes a fallidas en última versión publicada 2.2.3 https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/releases.
Si el error vuelve a aparecer en está versión por favor informarnos.

**Comment by melvinvita** [comment]
Hola @a1b4 , cumplo con lo solicitado e informo que el problema persiste, de hecho parece haberse incrementado, muestro evidencia. Todos con 2 o 3 días de diferencia entre el cambio a "Completado" y el cambio automático a "Fallido".

Espero puedan dar con el error pronto, saludos.

![screenshot-camillaschile cl-2019 05 06-08-15-22](https://user-images.githubusercontent.com/47744981/57225445-5f10c900-6fda-11e9-9939-aeec6dded7bf.png)
![screenshot-camillaschile cl-2019 05 06-08-22-32](https://user-images.githubusercontent.com/47744981/57225446-5fa95f80-6fda-11e9-9724-4fed5a13506a.png)
![screenshot-camillaschile cl-2019 05 06-08-23-20](https://user-images.githubusercontent.com/47744981/57225447-5fa95f80-6fda-11e9-82cc-25115e64403d.png)
![screenshot-camillaschile cl-2019 05 06-08-24-17](https://user-images.githubusercontent.com/47744981/57225448-5fa95f80-6fda-11e9-94e7-2f5ce6f15edd.png)
![screenshot-camillaschile cl-2019 05 06-08-25-18](https://user-images.githubusercontent.com/47744981/57225449-5fa95f80-6fda-11e9-8f25-37a0248d6556.png)
![screenshot-camillaschile cl-2019 05 06-08-25-58](https://user-images.githubusercontent.com/47744981/57225451-6041f600-6fda-11e9-90d0-5a62c3f1270b.png)
![screenshot-camillaschile cl-2019 05 06-08-28-38](https://user-images.githubusercontent.com/47744981/57225452-6041f600-6fda-11e9-8c19-4197d321ddc2.png)

**Comment by a1b4** [comment]
@melvinvita Hola, has cambiado el plugin por la última versión?

**Comment by ricardogonzalezcari** [comment]
El viernes instale la nueva versión y hasta hoy no tenido cambio de estados en pedidos completados.
Por ahora va bien ;)
saludos.

**Comment by melvinvita** [comment]
> @melvinvita Hola, has cambiado el plugin por la última versión?

Si, 2.2.3



> El viernes instale la nueva versión y hasta hoy no tenido cambio de estados en pedidos completados.
> Por ahora va bien ;)
> saludos.

Me alegra que esté funcionando para ti, yo tengo esos 7 casos.

Viendo bien las fechas, los pedidos se hicieron con la versión anterior del plugin, pero ya para el 3/05 estaba la nueva versión, también observo que los pedidos fueron cancelados casi a la misma fecha y hora.

**Comment by a1b4** [comment]
@melvinvita Hola, podrías por favor seguir monitoreando esto un par de días y contarme como va, para retomar este issue si persiste. gracias!

**Comment by melvinvita** [comment]
> @melvinvita Hola, podrías por favor seguir monitoreando esto un par de días y contarme como va, para retomar este issue si persiste. gracias!

Por supuesto, les comento en la semana, muchas gracias por tu atención.

@ricardogonzalezcari gracias también por reportar el avance de tu sitio.

**Comment by leoBonilla** [comment]
Hola, estamos trabajando con este plugin y tenemos problemas en el ambiente de produccion hay intermitencia y nos esta arrojando errores cuando se genera el pago. Hay alguna solucion para este problema.

La version que estamos usando es la 2.7.1
La version de woocommerce es la 3.5.2 

En la pagina después de procesar el pago dice error 500, página no encontrada
  
![Captura de pantalla 2020-05-27 a las 4 02 40 p m](https://user-images.githubusercontent.com/3891558/83066876-b9405a00-a033-11ea-9471-39660f76c80c.png)
