### ISSUE TITLE
Funciona pero No aparece la configuración 

### ISSUE THREAD

**Issue by sonda123** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#36]
Con la actualización 2.2.2 ya no aparece la configuración de transbank. 
El pago funciona pero la parte de ajustes quedó en blanco. Voy adjuntar imágenes para explicar mejor.
Voy a woocommerce, luego Ajustes, luego a Pagos, Activo el medio de pago Transbank Webpay Plus, y hago click en Gestionar, y no aparece nada… Antes habían informaciones y ahora desapareció todo. No sé si es normal, o si es un problema, Bueno eso era lo que quería avisar. Gracias.
![Screen Shot 2019-04-09 at 22 05 48](https://user-images.githubusercontent.com/47185145/55846657-7f04b800-5b14-11e9-8bcf-8555359e74f1.jpg)
![Screen Shot 2019-04-09 at 22 06 02](https://user-images.githubusercontent.com/47185145/55846658-7f9d4e80-5b14-11e9-9b42-81681424593a.jpg)

**Comment by ffiebig** [comment]
Hola @sonda123 me podrías decir cual version de PHP, Wordpress y WooCommerce estás utilizando ?

**Comment by sonda123** [comment]
Hola Felipe. 
Gracias por tu contacto. 
Te comento que hice un reseteo completo del servidor y volvió a normalidad. 
uso php 7.1.28 wordpress 5.1.1 y woocommerce 3.5.7 
Saludos

**Comment by ffiebig** [comment]
Me alegro que lo hayas solucionado.
Voy a cerrar el issue, pero quedamos atentos por si vuelve a surgir el problema.
