### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by rodrigofloresordenes** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#37]
Hola!

Hay fecha para compatibilidad con PHP 7.2. Un cliente contrató y pagó en Wordpress.com y no hacen downgrade de versión.

Este error es el que se depliega al intentar activar el plugin:

Fatal error: require_once(): Failed opening required '/wordpress/core/5.1.1/wp-content/plugins/woocommerce-transbank/vendor/autoload.php' (include_path='/:.') in /srv/htdocs/wp-content/plugins/woocommerce-transbank/webpay.php on line 28

**Comment by svaldesm** [comment]
Muy necesario. Ya vamos en PHP 7.3 y todavía nada.

**Comment by escafandra-web** [comment]
Tengo el mismo problema. Contraté wordpress.com y aparentemente la versión que tengo tiene un PHP más avanzado que esta version del pluggin. Desde wordpress.com dicen que no se puede degradar la version de PHP, desde transbank dicen no tienen una version nueva del pluggin. Ayuda por favor!

**Comment by rodrigofloresordenes** [comment]
Si te sirve de algo, lo que hice con un par de clientes fue:

1. Solicitar reembolso de wordpress.com, porque ellos no dan soporte para la versión de PHP.
2. Habilitar un contenedor de Google Compute Engine e instalar wordpress.

Si personalizas bien el contenedor, te sale muchísimo más barato y funciona muchísimo mejor que wordpress.com

:)

**Comment by escafandra-web** [comment]
Muchísimas gracias por la info. Se agradece un montón.  ;)
No poseo mucho conocimiento de "Google Compute Engine" por lo que se me hace difícil hacer lo q sugieres. Sin embargo, y esto es sólo una pregunta, ¿no debiese Transbank mantener actualizado sus pluggins?

**Comment by rodrigofloresordenes** [comment]
Totalmente de acuerdo, y de hecho, la versión 7.1 ya data de bastante tiempo. Sin embargo, como tbk no lo hace, y el cliente siempre necesita todo a la brevedad, es bueno tener alternativas. Y a veces te sorprendes con servicios que hay mucho mejores y mas baratos ;)

Por otra parte, wordpress.com es demasiado estricto. Por lo general los servicios de hosting tienen cierta tolerancia a versiones anteriores, pero wordpress.com no transa con eso.

**Comment by escafandra-web** [comment]
Aunque es lamentable lo rígido que es el sistema wordpress, encuentro que es publicidad engañosa de parte de Transbank decir que se trabaja con Wordpress cuando no trabajan con las ultimas versiones de los sistemas. 
Nuevamente mil gracias!

**Comment by ricardogonzalezcari** [comment]
Hola a todos!
Llevo un par de meses con las ultimas versiones del plugin corriéndolo bajo php7.3 y wordpress 3.5.8 y en 3 ecommerce y no hemos visto ningún problema, como tampoco hemos visto logs corriéndolo en debug para descartar errores.

Podria asegurar que el plugin es compatible con php7.2 y 7.3 al menos de forma no oficial.

Saludos

**Comment by svaldesm** [comment]
Hoala @ricardogonzalezcari muchas gracias por la información. 

Cuál es el commit que da soporte a PHP 7.3? Porque la última vez que probé no me funcionaba.

Muchas gracias!

**Comment by felipelavinz** [comment]
Por algunas pruebas que he hecho, me parece que el problema es la dependencia de mcrypt, que en algunas distribuciones (Ubuntu, Debian) no tiene una versión disponible en repositorios para PHP 7.2 (correctamente, ya que según la documentación oficial de PHP [esa librería está obsoleta](https://php.net/manual/en/migration71.deprecated.php#migration71.deprecated.ext-mcrypt)), sino que hay que instalar desde PECL... que tampoco tiene una versión disponible para 7.2 en repositorios :disappointed: 

... por lo tanto, a menos alguien prefiera compilar PHP desde código fuente, no es nada de fácil poder lograr la compatibilidad entre 7.2 y este plugin... a menos que se reemplace esa dependencia por **sodium**, que al parecer sería el paso lógico

**Comment by svaldesm** [comment]
@felipelavinz al menos yo la estoy usando en PHP 7.3 y me funciona perfecto! y cuando probé en PHP 7.2 tampoco tuve problemas.
Estoy en Vultr (a través de Cloudways), y al parecer tengo Debian 8 (según lo que pude averiguar, la verdad no soy experto).

Saludos!

**Comment by felipelavinz** [comment]
@svaldesm toda la razón, estaba utilizando una versión anterior del plugin cuando actualicé de 7.1 a 7.2, con la versión más reciente del plugin no tuve problema

**Comment by a1b4** [comment]
Hola a todos la [ultima versión](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/releases/latest) publicada del plugin ya soporta php 7.2
