### ISSUE TITLE
Cobrar en USD

### ISSUE THREAD

**Issue by arielesponda** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#38]
Hola, como puedo hacer para modificar el plugin y cobrar en USD?

**Comment by a1b4** [comment]
Hola @arielesponda para contribuir a grandes rasgos debes hacer los siguiente

- Fork del repositorio
- Clonar el repositorio
- Actualizar la rama master
- Crear una rama
- Hacer los cambios
- Hacer un Pull Request

usamos ingles tanto para las ramas como para los commits.

**Comment by a1b4** [comment]
@arielesponda daré por cerrado este issue ya que se ha contestado la pregunta sobre como contribuir. Como información adicional Transbank ya no trabaja con códigos de comercio en dólares, por tanto la opción desplegar los precios en dólares y convertir a CLP al momento del cobro.

Saludos.
