### ISSUE TITLE
El enlace que has seguido ha caducado.  Por favor, inténtalo de nuevo.

### ISSUE THREAD

**Issue by NonStopKilling** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#39]
El enlace que has seguido ha caducado.

Por favor, inténtalo de nuevo.

<img src="https://i.imgur.com/DBYfvux.png">

Me sale eso al subir el plugin a mi instalación reciente de wordpress 
WooCommerce Versión 3.5.5
WordPress 5.1.1 

La versión del plugin 2.0.0 se instala sin ningún inconveniente.

**Comment by TCattd** [comment]
El problema, me parece, es que la gente de Transbank acá está empaquetando el plugin sin un directorio "root" en el plugin.
WordPress requiere que cada plugin empaquetado como zip, venga dentro con el directorio raíz que ocupará el plugin (slug) dentro de WordPress.

Así es como vienen actualmente todos los zip de los [releases](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/releases):
http://prntscr.com/ngsxan

Sin una carpeta de raíz, el slug, para el plugin.

Así es como debería venir:
http://prntscr.com/ngsxuo

Notar la carpeta raíz del plugin, que será el slug del mismo una vez instalado.

Sería ideal que Transbank arreglase los zip de los releases, para permitir la instalación del plugin directamente como subida de un zip desde el mismo wp-admin, y forzaran un slug único, estándar, para toda instalación del plugin.

Si quieres subir el plugin como zip hoy vía wp-admin, tienes que descomprimirlo en local primero (en tu pc), meter los archivos que vienen en el zip dentro de una carpeta con el nombre woocommerce-transbank, y luego comprimir esa carpeta en zip.

Ese zip nuevo lo puedes subía a través del wp-admin sin inconvenientes.

Espero ayude ;)

**Comment by NonStopKilling** [comment]
Muchísimas gracias maestro por tu tiempo y sabiduría. Probaré y te comento como me va, muchas gracias

**Comment by a1b4** [comment]
@NonStopKilling Hola, has podido solucionar el tema?
Algunos usuarios han presentado este error debido a configuraciones de su hosting.

saludos.

**Comment by TCattd** [comment]
@NonStopKilling , otra cosa que debes revisar es el tamaño del upload permitido en tu hosting.

Desde la renovación del plugin, cuando lo metieron a GitHub (no recuerdo en qué momento fue), Transbank comenzó a incluir librerías vía composer en el plugin.

El pero de eso, es que hoy incluyen dos que suman bastante al peso del plugin.

/vendor/apache/ suma 1.7 megas al plugin.
/vendor/tecnickcom/ suma casi 32 megas al plugin.

Eso es el principal culpable para que el plugin pasara de pesar 700 kilos en la versión 2.0.4, a 17 megas en la versión 2.2.4.
Y es el porqué de mucha gente que no puede instalar el plugin vía el wp-admin. No es común ver un hosting (shared) que permita, por default, subir archivos de ese tamaño.

Entiendo que necesiten estas librerías en el plugin.

/vendor/tecnickcom/ lo usan para generar PDFs, me imagino que para el informe que se puede hacer en la configuración del plugin.
Pero, incluyen /vendor/tecnickcom/tcpdf/example/ que no son necesarios, carpeta que pesa 1.7 megas.

Además incluyen /vendor/tecnickcom/tcpdf/fonts/ fuentes que me imagino no necesitan para un informe que es técnico (su utilidad radica en eso, lo técnico, no las fuentes), y esa carpeta por si sola pesa casi 29 megas.

@NonStopKilling 
El error que mencioné, el del slug del plugin, lo arreglaron recién en la 2.2.4.
Ver commit:
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/commit/62e52eb96a9aff18b6b8a875d73efdb41d59cbfa

Si ese era tu problema, no era tu hosting. Con la versión 2.2.4 del plugin, no deberías pegar en eso.

Aún debes revisar el upload máximo de tu hosting/WordPress.
Una forma sencilla de ver cuánto permite subir tu hosting en un solo archivo, es abrir la librería de medios de WordPress en /wp-admin/upload.php
Ahí presiona el botón para agregar un nuevo archivo. WordPress mostrará cuánto te permite subir en un solo archivo:
http://prntscr.com/noye7j

Si no puedes subir archivos de por lo menos el peso del plugin, 17 megas y fracción (eso pesa el zip de la 2.2.4, compreso), no vas a poder subir nunca el plugin desde el wp-admin, y tendrás que subir el plugin directo vía ftp, sftp, ssh, cpanel u otro medio, a la carpeta /wp-content/plugins/ de tu WordPress.

Sugerencia para Transbank:

Sería ideal que tuviesen un sistema de build para los releases que hacen del plugin, y en ese proceso del build removieran lo que no necesitan de las librerías en /vendor/.
Hasta un script en bash les serviría para preparar el plugin para release, limpiar y comprimir, automático.

No tiene sentido que el plugin pese casi 35 megas (17 megas y algo compreso), casi exclusivamente por la librería de PDF que solo se usa en el wp-admin para debug, y por ejemplos y fuentes que no son necesarias.

**Comment by a1b4** [comment]
@NonStopKilling gracias por tus sugerencias, las consideraremos como mejoras a los plugin.

Saludos.

**Comment by a1b4** [comment]
@NonStopKilling como no hemos obtenido respuesta cerraremos este issue, por favor cuentanos si este problema persiste para re-abrirlo.

saludos.

**Comment by NonStopKilling** [comment]
Muchas gracias a todos por su tiempo, pude solucionar el inconveniente, perdón por no avisar!
