### ISSUE TITLE
No se muestra "Detalles de pago" al finalizar compra exitosamente (order-received)

### ISSUE THREAD

**Issue by soyniqolas** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#41]
¡Hola!
Al momento de realizar una compra exitosa me percaté que en la página order-received (thank_you) no es mostrada la información "Detalles de Pago", que debería verse y viene incluida en el plugin.

**Ejemplo de como debería verse:**

<img width="1057" alt="demo9" src="https://user-images.githubusercontent.com/16521415/56777490-eae75180-679f-11e9-9cd3-f714caea451d.png">

### Solución:
En el archivo webpay.php, línea 213, se guarda en la sesión la información de la transacción:
`WC()->session->set($order_info->get_order_key(), $result);`

Si la guardamos en una variable llamada `$order_info->get_order_key()` (que al ejecutarse devuelve algo como: _wc_order_7iMqJCdoBIlxB_) aparece el problema.

Si guardamos en la misma variable pero terminada en cualquier otra cosa, por ejemplo, `$order_info->get_order_key() . '_info'` (quedaría como: _wc_order_7iMqJCdoBIlxB_info_) el problema se soluciona (reemplazando obviamente cualquier lectura de la variable en la sesión con su nuevo nombre).

De esta manera, se deben modificar:

Línea 213: `WC()->session->set($order_info->get_order_key() . '_info', $result);`
Línea 812: `WC()->session->get($order_info->get_order_key() . "_info") == "") {`
Línea 829: `$finalResponse = WC()->session->get($order_info->get_order_key() . '_info');`
Línea 830: `WC()->session->set($order_info->get_order_key() . '_info', "");`

Y volvería a mostrar los detalles de la transacción nuevamente en la página de éxito.

Ejemplo de como se ve funcionando:
![Captura de pantalla 2019-04-25 a la(s) 21 30 29](https://user-images.githubusercontent.com/16521415/56777814-639add80-67a1-11e9-8959-c0d9ddfcd59b.png)

Versión de Wordpress: 5.1.1
Versión de WooCommerce: 3.6.2
Versión de Plugin Transbank: 2.2.2

**Comment by a1b4** [comment]
@soyniqolas buenos días, gracias por reportar el error. Por lo que veo has modificado el código del plugin para solucionarlo, te gustaría hacer ese aporte en forma de Pull Request al repositorio? 😃 

Saludos.

**Comment by gonzunigad** [comment]
Gracias por tu reporet. 

@soyniqolas probé en la última versión del plugin y efectivament veo la sección Detalles del pago, por lo que quizás ya está resuelto si alguna vez falló. 
![image](https://user-images.githubusercontent.com/1103494/74302597-d4fa4b80-4d35-11ea-9fcb-2bab2f0b55c8.png)

Cerraré este issue, pero si crees que aún no está resuelto, puedes comentarnos para volver a abrirlo 👌
