### ISSUE TITLE
No se muestra mensaje de error ante transacción rechazada

### ISSUE THREAD

**Issue by soyniqolas** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#42]
¡Hola!
Al momento de realizar una transacción y que esta salga rechazada no se le muestra al cliente un mensaje de error indicando el motivo. 

Actualmente solo aparece este resumen que le permite nuevamente iniciar el pago (pero no le indica que el anterior fue rechazado). Si el pago se rechaza se redirecciona automáticamente a  "order-pay".

![Captura de pantalla 2019-04-25 a la(s) 22 35 35](https://user-images.githubusercontent.com/16521415/56779916-2b000180-67ab-11e9-8c8d-e8390c5a364d.png)

La solución más efectiva (y lógica) que encontré es redireccionar al usuario a la página "order-received" (sí, la misma página que redirecciona en caso de transacción exitosa). 

Al redireccionar a esta página el usuario verá un mensaje indicándole que no se ha procesado su pago, junto con la información de WebPay. Además, le permitirá volver a pagar.

![Captura de pantalla 2019-04-25 a la(s) 22 35 12](https://user-images.githubusercontent.com/16521415/56780030-ac579400-67ab-11e9-98e3-3eb1b747b7f0.png)

Esta solución se realiza modificando el siguiente código:
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/blob/b6808157c2921b72c827aceb5c76b3e6371d2974/woocommerce-transbank/webpay.php#L236

Por lo siguiente:
`self::redirect($order_info->get_checkout_order_received_url(), array("token_ws" => $token_ws));`

De esta forma debería el cliente poder ver un mensaje de error en caso de transacción rechazada.

¡Saludos!

**Comment by ricardogonzalezcari** [comment]
Hola @soyniqolas 
Probe tu arreglo y funcionó perfecto, también teníamos este problema y ahora está solucionado.

Podrías hacer un Pull Request para incluir el cambio en la próxima versión, nos sería útil a todos.

Saludos!

**Comment by ffiebig** [comment]
@soyniqolas gracias por reportar el problema y proponer una solución. Se ve bastante bien, me sumo a la sugerencia de @ricardogonzalezcari para que hagas un Pull Request para que mezclemos tu arreglo 😁

**Comment by soyniqolas** [comment]
Me encantaría hacerlo, pero aún no se usar Github 😪

**Comment by ffiebig** [comment]
@soyniqolas si aun te interesa puedes guiarte del siguiente articulo

https://medium.com/@andresfernandosaa/c%C3%B3mo-hacer-mi-primer-aporte-en-la-comunidad-de-github-d644ae88c317

Si aun tienes dudas podemos guiarte para que hagas el aporte 😁

**Comment by gonzunigad** [comment]
@soyniqolas Si te sigue interesando hacer un PR, te dejo una guía por si no lo has hecho antes: 
Al hacerlo, aparecerás como contribuidor en el repositorio :)

1. - [Hacer un fork](https://help.github.com/es/github/getting-started-with-github/fork-a-repo) de este repositorio. Esto creará una copia en tu propia cuenta de github. 
2. - Descargar/clonar este nuevo repositorio en tu computador
3. - Crear un nuevo branch (algo como `fix/database_prefix`)
4. - Hacer los cambios necesarios en ese branch, hacer commit y subir el branch a tu repositorio (`git push ...`)
5. -  Si ya tienes un branch creado en tu fork, ya puedes hacer un Pull Request en este repositorio siguiendo [estas instrucciones](https://help.github.com/es/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

Si tienes dudas, puedes hablarme por el slack de la comunidad de TransbankDevelopers. Puedes unirte acá: https://join-transbankdevelopers-slack.herokuapp.com/

**Comment by gonzunigad** [comment]
En todo caso, hoy aparece esto en una transación rechazada: 
![image](https://user-images.githubusercontent.com/1103494/74302783-72ee1600-4d36-11ea-8230-a6f05f81e39d.png)
