### ISSUE TITLE
Compatibilidad WC 3.6.2 ?

### ISSUE THREAD

**Issue by sonda123** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#45]
Se solicita por favor confirmar si la última versión 2.2.3, corrección 2.2.4 es compatible con la actualización de woocommerce versión 3.6.2  
Gracias.

**Comment by sonda123** [comment]
![Screen Shot 2019-05-07 at 18 21 54](https://user-images.githubusercontent.com/47185145/57342730-43a6da80-710e-11e9-9413-0613aff4e46b.jpg)
![Screen Shot 2019-05-07 at 18 22 02](https://user-images.githubusercontent.com/47185145/57342731-43a6da80-710e-11e9-820d-b1396425582d.jpg)

**Comment by sonda123** [comment]
![Screen Shot 2019-05-07 at 21 21 48](https://user-images.githubusercontent.com/47185145/57342763-794bc380-710e-11e9-9dea-2da25a9a9645.jpg)

**Comment by a1b4** [comment]
@sonda123 buen día, has realizado pruebas de actualización. Por nuestro lado hemos realizados las pruebas exitosas con la versión de wooCommerce 3.6.2 y wordpress 5.2. 
Si has obtenido algún problema o error te pido por favor dejar mayor detalle.

Saludos.

**Comment by a1b4** [comment]
Hola, la [ultima versión del plugin](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/releases/latest) es compatible con woocommerce 3.6.3
