### ISSUE TITLE
Cambiar imagen 

### ISSUE THREAD

**Issue by ricardogonzalezcari** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#47]
Estimados,
No es un problema del punto de vista técnico, pero si visual.

Será posible cambiar esta imagen del método de pago:
![Logo_Webpay3-01-50x50](https://user-images.githubusercontent.com/44407695/57242326-3a7c1780-7001-11e9-89f0-76858d12160b.png)

¿Por esta?
![logo-webpay-3](https://user-images.githubusercontent.com/44407695/57242215-f6891280-7000-11e9-99fd-c24867591cd5.png)

Gracias!

**Comment by a1b4** [comment]
@ricardogonzalezcari Buen día, podrías indicarnos el motivo por el cual es necesario el cambio de la imagen, para poder validarlo con Transbank.

Saludos.

**Comment by ricardogonzalezcari** [comment]
Hola @a1b4!
El motivo es bien sencillo por un lado mis clientes han hecho ese alcance y finalmente he tenido que cambiarla en el plugin, por otro lado, la imagen es bastante pequeña y tiene poca presencia, ademas de pixelada y muy pequeña, que ni siquiera se alcanza a apreciar los iconos de las tarjetas y menos el logotipo de transbank.

**Comment by melvinvita** [comment]
Por otro lado, hay una nueva sección en transbank developers con logos oficiales, podrían usarse para referencia
https://www.transbankdevelopers.cl/brand-assets

**Comment by ricardogonzalezcari** [comment]
Ya revisé la seccion y creo que no encontre ninguna que se adaptara para imagen de metodo de pago, por eso creé la imagen la cual estoy utilizando con la linea gráfica de Transbank.

Ojala la puedan cambiar, de seguro sera una mejora para todos los demas.

Saludos

**Comment by jprush76** [comment]
Hola @ricardogonzalezcari , sabes hice el cambio de imagen que mencionas en mi sitio web y realmente cambia la presencia del método de pago por sobre los otros. ¡Se ve muy bien!
Muchas gracias por el aporte, realmente deberían pensar en cambiar la imagen en el plugin.
Saludos, Jaime

**Comment by ricardogonzalezcari** [comment]
@jprush67
Es notable el cambio, que bueno que te sirvió.
Ojalá lo agreguen al próximo release.

Saludos

**Comment by ricardogonzalezcari** [comment]
Hola @a1b4 
En que quedó esto?

**Comment by a1b4** [comment]
hola @ricardogonzalezcari me encontraba de vacaciones cuando realizaste la pregunta 😅 .
Hemos levantado este tema como una mejora a los plugin, espero pueda salir pronto.

saludos.

**Comment by gonzunigad** [comment]
Como referencia, con el cambio quedaría así (imagen tomada usando e tema storefront): 
![image](https://user-images.githubusercontent.com/1103494/73305931-eef64300-41f9-11ea-93a4-763b866d467e.png)

**Comment by gonzunigad** [comment]
En este PR se realiza el cambio, en caso de querer implementar el cambio: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/pull/80

**Comment by gonzunigad** [comment]
Cambio aceptado en PR #80  👌

**Comment by unkchile** [comment]
Hola chicos, pueden indicarme el procedimiento para cambiar el logo, nose que pasó en mi woo que ahora el logo no se ve, el link del logo cambió a http://portal-estatico-wcs.s3-website-us-east-1.amazonaws.com/comp/img/Logo_Webpay3-01-50x50.png
Me gustaría dejarlo como el que mostro GONZUNIGAD
MUchas gracias!!!
