### ISSUE TITLE
Auto-actualización del plugin. ¿Repos WordPress.org?, o GitHub directo.

### ISSUE THREAD

**Issue by TCattd** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#49]
Estimados,

Agradezco un montón que estén manteniendo el plugin al día.
De verdad, es grato ver releases nuevos resolviendo issues relevantes:
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/releases
Muy bueno.

(Ojalá no se olviden de [PHP 7.2](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/issues/37) y 7.3, por favor)

El problema es como mantener al día a diversos clientes a los que se los ha integrado a vuestra plataforma, a través de este plugin, si este no se auto-actualiza.
(Y sin requerir el uso de herramientas de terceros)

Ignoro cuál es el motivo por el que este plugin no lo ofrecen directamente en wordpress.org. O si lo harán en un futuro (cercano ojalá).
Es la forma oficial para que los plugins instalados en WP se auto-actualicen.

Pero si no lo van a hacer, ¿podrían considerar el implementar una auto-actualización desde GitHub?
Por favor.

Es común, para plugins pagados, ofrecer updates de todos modos (ver Advanced Custom Fields Pro, Elementor Pro, etc.), y ellos no alojan esos plugins pagados en wordpress.org para permitir de todos modos el auto-actualizado de ellos.

Ya tienen el plugin acá en GitHub (eso por si solo es un gran salto). Existen librerías listas y/o guías de como implementar esto:
https://github.com/YahnisElsts/plugin-update-checker
https://github.com/radishconcepts/WordPress-GitHub-Plugin-Updater
https://github.com/pdclark/git-plugin-updates
https://code.tutsplus.com/tutorials/distributing-your-plugins-in-github-with-automatic-updates--wp-34817
etc.

Podrían aprovechar la misma flexibilidad que da WordPress respecto a los updates, para permitir que vuestro plugin se auto-actualice igual que todo el resto que está en los repos de wordpress.org, pero manteniéndolo acá en GitHub (si es que no les interesa o no pueden publicarlo en wordpress.org).

Por favor.

PD: no puedo ayudar directamente a esto, aunque me encantaría poder enviar un PR con la funcionalidad lista, porque para poder probar una integración así, que traiga los updates del plugin desde GitHub, probablemente se va a requerir acceso al repo directamente para poder ajustar los releases a un formato específico, o tag-gear los nuevos releases, dependiendo de como quieran implementar los updates (si usan una librería pre-hecha, su configuración, o vuestra propia solución). Y no sería pertinente dar acceso a este repo a cualquier NN :)

**Comment by a1b4** [comment]
@TCattd muchas gracias por la información, toda contribución incluyendo la información y recomendaciones son de gran ayuda. este es un tema en el que esperamos poder ir mejorando. :)

Saludos.

**Comment by felipelavinz** [comment]
Ojalá también consideren la posibilidad de añadir el plugin a Packagist; con GitHub es muy sencillo hacer la integración y así al menos existiría la posibilidad de actualizar con composer

**Comment by TCattd** [comment]
Buenas,

¿Habrá algún ETA respecto a este issue?. Por favor.

Pregunto, porque hoy soporte de Transbank (vía email) nos pidió simplemente "mantener actualizado el plugin" ante el reporte de un error (serio para el cliente la verdad) puesto que lo que reportamos ya había sido resuelto según soporte.

Tener que revisar la página de releases del repo a mano, todos los días, para saber si hay o no actualizaciones, y luego tener que instalar el zip a mano en cada WP de cada cliente al que se  le ha ayudado con la integración, es un tema de locos la verdad. De locos.

Y no siempre hay acceso (total o parcial) en todos los sitios integrados como para automatizarlo de otra forma (FTP, SSH, Composer, o algún Dashboard como MainWP, InfiniteWP, etc.).

Con decenas de integraciones así, esto se vuelve un disparate.

Se agradece desde ya el tiempo.

Esteban

**Comment by gonzunigad** [comment]
Les comento que se está trabajando activamente en esto, pero requiere de un cambio de nombre en el plugin. Ya no puede llamarse 'woocommerce-transbank' como está ahora, porque con ese nombre no se puede subir a wordpress.org. Este cambio de nombre requiere de un desarrollo para que al instalar el plugin con el nuevo nombre este desactive la versión anterior, para así no generar conflictos de código. 

No podemos entregar un ETA, pero ese desarrollo está bastante avanzado.

**Comment by toby12222** [comment]
como chucha se puede borrar cada cierto tiempo el log de transbank

**Comment by gonzunigad** [comment]
Hola @toby12222 . El plugin no tiene esa funcionalidad. Si quieres, podrías crear un issue soliccitandolo para quee lo analicemos oficialmente ;)

**Comment by gonzunigad** [comment]
Hola! Finalmente este plugin no estará listado en wordpress.org, pero pueden solicitar esto mismo en el nuevo plugin REST: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest

Es probable que si lo hagamos en ese nuevo plugin :)

**Comment by gonzunigad** [comment]
Solo para dejar registro acá, el nuevo plugin REST ya está publicado en el repositorio de plugins oficial de Wordpress: https://wordpress.org/plugins/transbank-webpay-plus-rest/

¡A cambiarse si no lo han hecho todavía!
