### ISSUE TITLE
No se puede realizar la transacción de pago

### ISSUE THREAD

**Issue by roshrnair** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#50]
Al hacer clic en "Realizar pedido" "Place Order"
Me lleva a pagar por pantalla de pedido. Permanece allí durante un tiempo de registro y luego me muestra el error "No se puede acceder al sitio" para la página siguiente.
https://webpay3gint.transbank.cl/webpayserver/initTransaction.

Por favor ayuda.

**Comment by a1b4** [comment]
Hola @roshrnair podrías entregarnos mayor evidencia del error?
Versiones de php, wordpress y woocommerce. 
Pasas para replicar el error, patallas o logs del error.

saludos.

**Comment by roshrnair** [comment]
PHP Version: 5.6.39
WooCommerce: 3.6.2
Tranbank Plugin : 2.2.4

OpenSSL: 1.0.2q
Simple XML: 0.1
Soap: 5.6.39
Dom: 20031129

Log:

[2019-05-17 09:44:32] [INFO ] INFO: initTransaction - amount: 1911, sessionId: 5cde827fa1f75, buyOrder: 3972, txDate: 17-05-2019, txTime: 09:44:32 

[2019-05-17 09:44:33] [INFO ] INFO: initTransaction - initResult: {"return":null,"token":"edb72c34afe2fed8f487e11fbee0b2d972fa86cbd92beab268a971d04d6efbef","url":"https:\/	\/webpay3gint.transbank.cl\/webpayserver\/initTransaction"}

Gracias
Rosh

**Comment by roshrnair** [comment]
¿Puede por favor ayudar en este tema.
Gracias

**Comment by a1b4** [comment]
@roshrnair hola, puedes ingresar al sitio https://webpay3gint.transbank.cl/webpayserver/initTransaction ? puedes enviarnos un pantallazo?

por el log que envías el inicio de la transacción se está realizando correctamente. por casualidad estás fuera de Chile?

**Comment by roshrnair** [comment]
Hola,
No, no puedo acceder al sitio. Estoy ubicado fuera de chile. Estoy desarrollando esta aplicación para mi cliente en Chile. El servidor de alojamiento se encuentra en Virginia, Estados Unidos.

Gracias

**Comment by a1b4** [comment]
@roshrnair puedes ingresar al slack de transbank para poder darte contactarte mas directo y darte acceso desde fuera d chile https://join-transbankdevelopers-slack.herokuapp.com/

**Comment by roshrnair** [comment]
Thank you . I have raised a request in slack.
