### ISSUE TITLE
Nueva transaccion Fallida

### ISSUE THREAD

**Issue by jprush76** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#51]
¡Hola! Les escribo porque ayer domingo volvimos a tener problemas con un pedido de woocommerce, el cliente realizó correctamente la transacción, el pedido quedó en estado "Procesando" y un minuto después se cambió automaticamente a "Fallido".
Este error se había corregido cuando actualizamos el plugin a la versión 2.2.3 pero al parecer volvió.

Nuestra config:
wordpress 5.2.1
woocommerce 3.6.3
transbank plugin 2.2.3
php version 7.0.33

Les dejo el pantallazo de las notas de pedido. Ojalá nos puedan ayudar con esto.

Saludos,
Jaime

![Error Transbank cambio de estado pedido a fallido](https://user-images.githubusercontent.com/17952983/58395797-e2d93680-8017-11e9-8c03-24673a691dec.jpg)

**Comment by a1b4** [comment]
Hola, este issue es igual al #56 por lo que cerraremos este para no tener issues duplicados.

Saludos.
