### ISSUE TITLE
Nuevamente pedidos fallidos con pagos procesados

### ISSUE THREAD

**Issue by melvinvita** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#56]
**Describe el bug**

Vuelve a aparecer el error del cambio de estado del pedido luego de ser completado #35 
Esta vez en un volumen mucho mayor, se verificaron todas las transacciones en Transbank con sus códigos de autorización.

**Comportamiento observado**

3 días después el pedido cambia de completado a fallido de forma automática. a veces solo horas después.
![screenshot-camillaschile cl-2019 06 06-11-34-57](https://user-images.githubusercontent.com/47744981/59046200-8ebc2680-884f-11e9-82d2-60c2a5343e37.png)
![screenshot-camillaschile cl-2019 06 06-11-37-10](https://user-images.githubusercontent.com/47744981/59046201-8f54bd00-884f-11e9-8895-cabc40c9c6b5.png)

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 2.2.5
- Woocommerce: 3.6.4
- PHP: 7.0.33

Tengo más de 15 pedidos con este problema, ya hay clientes reclamando por sus pedidos ya que por obvias razones los pedidos fallidos o cancelados no se toman en cuenta.

Saludos.
** EDITADO **
También ocurre esto muy seguido (cancelado muchas veces):
![can](https://user-images.githubusercontent.com/47744981/59047942-e1e3a880-8852-11e9-8b12-f925fa7311fc.png)

**Comment by melvinvita** [comment]
Parece que ya se está saliendo de control, un pedido de Abril cambió hoy 07-06-2019

![screenshot-camillaschile cl-2019 06 07-13-50-26](https://user-images.githubusercontent.com/47744981/59123495-54c05280-892b-11e9-9639-03dea80ab156.png)

**Comment by aquezada** [comment]
Me pasa exactamente lo mismo. ¿Algún FIX?

**Comment by a1b4** [comment]
Hola, volveremos a hacer la revisión del plugin para verificar que los pagos ya procesados no sean cambiados a cancelados.
De todas formas si alguien a obtenido o implementado un solución pueden realizar un aporte al repositorio open source.

Saludos.

**Comment by a1b4** [comment]
@melvinvita hola, podrías validar que los id de las ordenes no se estén reutilizando?
Nos encontramos en el proceso de replicar el error y cualquier información extra será de gran ayuda.

Saludos.

**Comment by melvinvita** [comment]
Hola @a1b4 ,en algunos casos si, en la empresa donde trabajo hemos rediseñado casi todos los sitios web y empezando los IDs desde cero prácticamente, es probable que algunos se repitan.

**Comment by a1b4** [comment]
@melvinvita eres parte de la comunidad transbank developers en slack? me sería mas fácil matener la conversación por ese medio.

**Comment by a1b4** [comment]
@melvinvita @aquezada hemos [generado una versión del plugin](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/releases/tag/2.3.1) que valida el estado de orden antes de cambiar el estado, permitiendo el cambio solo si se encuentra pendiente. Les pido por favor confirmar que el problema se encuentra solucionado.

**Comment by aquezada** [comment]
Muchas gracias @a1b4

**Comment by kukimunuce** [comment]
@a1b4 @aquezada @melvinvita  Perdón, lejos estoy de entender muy bien, **pero desafortunadamente tengo el mismo problema**,  la solución reside en pisar el contenido de la carpeta woocommerce-transbank de @a1b4 con la que tengo dentro de la carpeta pluging del wordpress?

Muchas gracias, espero entiendan mi nivel de desconocimiento y me necesidad de solucionar el problema con urgencia.

**Comment by tecnomono** [comment]
Buenas noches , estoy teniendo el mismo problema , necesito algún contacto de alguna persona que vea este tipo de trabajo, y que haga mantencion web. Lo qué pasa que nuestro diseñador tuvo un accidente automovilístico, y está en recuperación. Por lo que a nosotros necesitamos esto con urgencia 
Dejare mi celular +56987690573 whatsap , Mi nombre es Luis Lavanderos . Si alguien me puede contactar por favor gracias
