### ISSUE TITLE
No puedo visualizar información en ajustes del plugin ni agregar certificado al cambiar a producción

### ISSUE THREAD

**Issue by fserrano88** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#58]
Hola!, Estoy pasando un sitio web de un cliente a producción, ya fueron validadas las pruebas con el equipo de transbank, pero ahora al pasar a producción, no me aparece el campo para añadir el certificado de transbank al cambiar el ambiente en los ajustes del plugin.

Tampoco me carga el modal cuando apreto el botón información.

Visualizando la consola, me arroja unos errores. Algunos son de dos CSS que no estan cargando, ya que están llamando a la ruta del servidor. (Adjunto pantallazo).

Estoy probando con la versión 2.3.0

![Captura de Pantalla 2019-06-22 a la(s) 13 55 26](https://user-images.githubusercontent.com/1197662/59967246-8b829500-94f5-11e9-9e23-0f4d4bd8e95e.png)
![Captura de Pantalla 2019-06-22 a la(s) 13 55 38](https://user-images.githubusercontent.com/1197662/59967251-8faeb280-94f5-11e9-8fac-ab418cc266fb.png)

<img width="761" alt="Captura de Pantalla 2019-06-22 a la(s) 13 48 33" src="https://user-images.githubusercontent.com/1197662/59967229-54ac7f00-94f5-11e9-914b-c4de52e268b9.png">

Quedo atento,
Gracias.

**Comment by a1b4** [comment]
@fserrano88 hola, puedes indicarnos las versiones del plugin, woocommerce y php que estás utilizando, además del navegador.

Saludos.

**Comment by fserrano88** [comment]
Hola!,

El plugin Transbank: versión 2.3.0. (Igual probé con la anterior.)
Woocommerce: Versión 3.5.6
PHP: PHP 7.1.30-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:43:40) ( NTS )

Estoy utilizando Chrome: Versión 74.0.3729.169 (Build oficial) (64 bits)
Para macbook.

Saludos

**Comment by melvinvita** [comment]
el tema de la ruta de los css y otros me pasa igual, sin embargo no tengo problemas con los campos del formulario.

![logtb](https://user-images.githubusercontent.com/47744981/60031648-2359bd80-9673-11e9-9f77-7f68cf505a9a.jpg)

**Comment by fserrano88** [comment]
@a1b4 Existe alguna manera de ingresar el certificado enviado por Transbank en la base de datos o en algún archivo (no quiero comenzar a analizar el código del plugin). De esta manera, independiente que siga el error y no aparezca el input al cambiar a producción, puedo dejar el sitio web operativo para el cliente.

Saludos y muchas gracias por la ayuda Alba.

**Comment by melvinvita** [comment]
@fserrano88 por que no integras con una versión anterior? mientras corrigen lo otro. no hay muchas diferencias entre la anterior y la última.

**Comment by a1b4** [comment]
@fserrano88 como menciona @melvinvita puedes utilizar la versión [2.2.5](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/releases/tag/2.2.5) mientras replicamos el error e implementamos alguna solución

Saludos.

**Comment by fserrano88** [comment]
@melvinvita @a1b4 Probé con todos los plugins de manera decreciente. Ninguno me mostró el modal de información. Desde el 2.2.1 me mostró el campo Certificado Transbank, pero solo porque no dependía del ambiente que seleccionara (siempre aparecía, incluso en integración).

Hace un año integramos transbank con el plugin de esa época (el 1.1.0 si no me equivoco, el cual tenía una restricción de php 5.6). En ese plugin me mostraba la información abajo de todo. 

Probé ahora también con firefox 67.0.4 para macos y tampoco provocaba un cambio. Antes de ponerme a actualizar woocommerce u otros aspectos del servidor, sería bueno intentar acotar el problema. 

Una pregunta. ¿Si utilizo el plugin 2.2.1 y copio el certificado transbank ahí, producirá algún otro problema mayor?. Mi cliente no utilizará stock ni cosas por el estilo, solo venderá planes para un gimnasio. Me interesa poder dejar su sitio operativo antes de que pasen los 10 días hábiles que da transbank para terminar la integración y así no partir todo el proceso de nuevo.

Quedo atento y gracias por la ayuda.

**Comment by a1b4** [comment]
@fserrano88 Hola, creo haber entendido tu problema, no corresponde a los css si no al campo del certificado de transbank, en ese caso la [versión 2.2.2](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/releases/tag/2.2.2) elimina ese campo de la configuración ya que el plugin lo configura automáticamente, por lo que no es necesario que lo ingreses, por lo que es correcto que el campo no aparezca en el formulario.

Por favor confimanos que el único campo que no visualizas es ese, o si tienes algún problema con los demás.

Saludos.

**Comment by fserrano88** [comment]
@a1b4 Hola, Uff es muy clarificador lo que me estás diciendo. Yo no sé si ustedes están en comunicación directa con validaciones, pero esto fue lo que me llegó al correo (el día 21/jun/2019) una vez aprobada la integración:

![logo-institutoMilenio](https://user-images.githubusercontent.com/1197662/60183118-9e49e200-97f3-11e9-903d-ac6cdcbb62ec.png)

Y me adjuntaron el certificado de transbank. Sería bueno que les informaran que eso no es necesario desde la versión 2.2.2.

De todas maneras, sigo sin poder visualizar el modal de "Información" del plugin, no me cargó en ninguna de las versiones. Esa información si la veia en el primer plugin como te señalaba en otro comentario (cuando integramos a comienzos del año pasado otro sitio), al parecer hay un problema para abrir el modal.

Quedo atento a eso, pero ya al menos estoy seguro de poder pasar a producción el sitio con tu último comentario.

Saludos y gracias por la ayuda.

**Comment by a1b4** [comment]
@fserrano88 muchas gracias por la información, vamos a comunicarlo para que no vuelva a suceder.

Saludos
