### ISSUE TITLE
Los pedidos cambian a estado cancelado

### ISSUE THREAD

**Issue by yistik** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#63]
**Describe el bug**

Una descripción concisa sobre el bug.

Todas las transacciones hechas por webpay luego de unos minutos quedan en modo cancelado, a pesar de haber sido pagadas correctamente. Al parecer esto tiene que ver con el plugin para envios Shipit, que dentro del proceso de compra pasa la orden a "pendiente" y luego de estar en pendiente, transbank lo toma y devuelve que la compra ha excedido el limite de tiempo.

Si aplica, agrega aquí capturas de pantalla que ayuden a explicar tu problema.

![compra-shi](https://user-images.githubusercontent.com/28583119/61501902-776c6f00-a99f-11e9-9b59-70d7e3c2fad3.jpg)

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: [ej. 2.3.1]
- Woocommerce: [ej. 3.6.5]
- PHP: [ej. 7.3]

**Contexto adicional**

- Shipit 1.1.1

**Comment by melvinvita** [comment]
Hola @yistik ,

Has intentado aumentar el tiempo en el que los pedidos pendientes de pago se cancelan automáticamente? 

Esta opción puedes encontrarla en:
`WooCommerce > Ajustes > Productos > Inventario "Mantener en inventario (en minutos)"`

De todas maneras, creo que el error viene de parte del plugin de Shipit, ya que cambia el estado del pedido a `Pendiente` después de recibir el pago. Intenta también consultando con ellos a ver si tienen alguna información.

Saludos

**Comment by yistik** [comment]
Hola Melvinita, te agradezco la respuesta.
Si ahora me di cuenta que esto también provoca el problema con otras plataformas, por lo que debe ser un problema particular del plugin de Shipit.
Cerraré el tema, gracias!
