### ISSUE TITLE
Error conectando a WebPay

### ISSUE THREAD

**Issue by melvinvita** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#64]
**Describe el bug**

Luego de llenar los campos y hacer clic en Realizar pedido, no redirecciona a transbank, se queda en la página del medio, adjunto screenshot.

**Comportamiento observado**

No redireccione y a veces muestra "ERROR: Ocurrió un error al intentar conectar con WebPay Plus. Por favor intenta mas tarde."

**Capturas de pantalla**

![Captura de pantalla (54)](https://user-images.githubusercontent.com/47744981/62317482-cdddb100-b467-11e9-8268-e6d84441d13b.png)
![Captura de pantalla (55)](https://user-images.githubusercontent.com/47744981/62317483-cdddb100-b467-11e9-92eb-4831e855404f.png)

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 2.3.1
- Woocommerce: 3.6.5
- PHP: 7.1

**Comment by legato-b** [comment]
Como lo solucionaron? Me encuentro en una situación similar

**Comment by ImTheGhostCode** [comment]
Estoy en la misma situación, alguien sabe de alguna solución o respuesta al problema? saludos.

**Comment by melvinvita** [comment]
Hola, esta falla si mal no recuerdo fue solucionada, fue un día que webpay al parecer tenía problemas.
También pudo ser (en nuestro caso) por el duplicado de números de pedido (buyOrder) en transbank, estos duplicados ocurrieron porque renovamos el sitio web y los ID's empezaron de nuevo. Para solucionar añadimos un par de letras al buyOrder para que no siguieran duplicándose.

**Comment by a1b4** [comment]
@melvinvita hola! has vuelto a presentar este problema?

saludos.

**Comment by melvinvita** [comment]
Hola @a1b4 , desde que cambié el buyOrder no ha vuelto a suceder. Todo marcha bien por el momento. Gracias

**Comment by dsovino-alma** [comment]
@a1b4 Hola, yo me encuentro en la misma situación ahora. Al finalizar la compra me está redireccionando a una página "order-pay page", sin abrir el popup.

Esto al sólo al intentar realizar la compra en Producción. En modo integración no tuve problemas.

**Comment by gonzunigad** [comment]
Entiendo que esto ya está resuelto y no es un problema actualmene. Cerraré este Issue. :)

**Comment by mueeznarejo** [comment]
> Hello, if I remember correctly this error was solved, it was a day that webpay apparently had problems. It could also be (in our case) due to duplicate order numbers (buyOrder) in transbank, these duplicates occurred because we renewed the website and the ID's started again. To solve it, we added a couple of letters to the buyOrder so that they would not continue to be duplicated.

Hi @melvinvita, I am facing the same issue, can you explain to me how to do this in steps?
