### ISSUE TITLE
Todo funciona. php7.2. Sin embargo Información, indica "Estado de PHP" "Error!: Version no soportada"

### ISSUE THREAD

**Issue by juanpablocarrillo** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#67]
La operación de pruebas, funciona bien. 
php7.2. Sin embargo Información, indica "Estado de PHP" "Error!: Versión no soportada"

**Para reproducir**

1. Configura plugin sobre Ubuntu 18.04, apache 2.4.29, con php 7.2.19 y woocomerce 3.7.1
2. Haz click en informacion del plugin "transbank Webpay"
3. Baja hasta "PHP"
4. Mira el Estado de PHP

**Comportamiento observado**

Aparece en informacion del plugin, bajo Estado de las Extensiones de PHP, bajo item PHP: Estado de PHP "Error! Version no soportada."  (en rojo)

**Comportamiento esperado**

Versión soportada, al ser PHP 7.2(.19) y cumplir con lo definido como características de compatibilidad del plugin, no deberia aparecer ese mensaje.

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/24797847/66682235-f72a7280-ec4a-11e9-9e72-c6cf20bedcae.png)

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 2.3.1
- Woocommerce: 3.7.1
- PHP: 7.2.19

**Contexto adicional**

La operación de las pruebas, fue exitosa.

**Comment by everquinones** [comment]
Hola también presento el mismo problema. Cuando cambio a la versión 7.2 de PHP el Plugin muestra ese mensaje, sin embargo el sistema de webpay funciona bien, pero el icono donde aparecen el logo de webpay y las tarjetas aparece por la mitad, a nivel visual genera confusión. Necesito usar la versión 7.2 porque Chilexpress tiene un plugin que exige esa versión, y con la versión 7.1 no es funcional.

**Comment by a1b4** [comment]
hola @juanpablocarrillo y @everquinones el plugin fue actualizado a php  7.2.19 en la versión 2.3.0, por lo que debe funcionar correctamente en esa versión de php, vamos a revisar lo que mencionan del mensaje para corregirlo. Gracias!

**Comment by gonzunigad** [comment]
Hola @juanpablocarrillo @everquinones. En la versión actual del plugin esto ahora funciona correctamente. Sería buenísimo si pudieran actualizar para poder confirmar que este issue está resuelto :)

**Comment by gonzunigad** [comment]
Esto ya está resuelto, por lo que cerraré este issue :)
