### ISSUE TITLE
Actualizacion de Plugin para Woocommerce de Versión 2.0.0 a 2.4.1

### ISSUE THREAD

**Issue by lowpez** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#72]
Estimado Equipo Transbank Developers,

Tengo esta incertidumbre en el proceso de actualización, y ya que no encontré guía, decidí sumar,
Verán, ya tengo en producción la plataforma, pero me han solicitado hacer el update.
Bastará con reemplazar los archivos existentes o requerirá una configuración extra?

Quedo atento a Consejos/experiencias,
Gracias!

**Comment by a1b4** [comment]
Hola @lowpez la recomendación es des-instalar el plugin e instalarlo de nuevo con la versión que deseas. Te recomiendo ver los cambios que se han hecho en el plugin para que no te sorprendas si hay cambios en la configuración, Por ejemplo, ya no es requerido el certificado de transbank ya que el sdk lo configura automáticamente, También ahora se puede configurar en que estado se desea que quede la orden cuando el pago es exitoso.
te recomiendo ingresar a la comunidad en slack https://join-transbankdevelopers-slack.herokuapp.com/ donde podrás hacer consultas ante cualquier duda o problema

**Comment by lowpez** [comment]
Gracias @a1b4 .
Ya me uní. Saludos!
