### ISSUE TITLE
El plugion no activa

### ISSUE THREAD

**Issue by haegl** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#73]
Saludos, instale la versión 2.4.1 del plugin de webpay para woocommerce, la version de php que tengo instalada en la 7.2.24, corriendo sobre ubuntu 18.04, woocommerce 3.8.0 y wordpress 5.2.4, cuando me dirijo al panel de woocommerce en la sección de ajustes/pagos, al hacer clic en el switch para activar el metodo de pago y guardar los cambios este no activa, permanece inactivo

![Captura de pantalla de 2019-12-08 14-10-28](https://user-images.githubusercontent.com/30668888/70389802-b2aa2180-19c4-11ea-8ab6-a9d6b67099d3.png)

en la sección de plugins de wordpress el plugin aparece activo

![Captura de pantalla de 2019-12-08 14-14-11](https://user-images.githubusercontent.com/30668888/70389843-2815f200-19c5-11ea-8dc2-0932a25df951.png)

el estado del plugin es el siguiente: alerta que la versión de php no esta soportada

![Captura de pantalla de 2019-12-08 14-16-49](https://user-images.githubusercontent.com/30668888/70389866-79be7c80-19c5-11ea-9f50-f684cc126b6e.png)

al validar la conexión esta responde de forma exitosa

![Captura de pantalla de 2019-12-08 14-17-55](https://user-images.githubusercontent.com/30668888/70389880-96f34b00-19c5-11ea-837d-693586608ac0.png)

de antemano agradezco su ayuda y colaboración

**Comment by gonzunigad** [comment]
Hola @haegl . Es posible que tengas WooCommerce configurado en una moneda que no sea CLP. En ese caso, creo que se desactiva el plugin. ¿Podrías confirmar si no es ese el problema?

**Comment by jmmeneses** [comment]
saludos, gracias por su respuesta, efectivamente el problema era la configuración de la moneda, ya que en principio el cliente quería definir el método de cobro como USD, al final en vista de que el plugin solo permite CLP se opto por configurar todo en CLP.

**Comment by gonzunigad** [comment]
Gracias por la confirmación 👌.
Dejaré cerrado el issue entonces.
