### ISSUE TITLE
No carga la información se queda en loading

### ISSUE THREAD

**Issue by almagency** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#74]
Buenas tengo un select con distintas regiones al cambiarlo antes  en la seccion de webpay  iban cambiando los montos segun las regiones ahora se queda en un eterno loading.

<img width="1109" alt="Captura de Pantalla 2019-12-17 a la(s) 09 33 54" src="https://user-images.githubusercontent.com/57400597/70995932-76577f00-20b0-11ea-944c-9a848e492887.png">

<img width="439" alt="Captura de Pantalla 2019-12-17 a la(s) 09 33 37" src="https://user-images.githubusercontent.com/57400597/70995934-76577f00-20b0-11ea-87a9-90286dbbb378.png">

**Comment by almagency** [comment]
Alguien puede contestar algo?

**Comment by jprush76** [comment]
Hola @almagency creo que tu problema es ajeno al plugin de webpay.. debes buscar el problema en tu configuración de zonas de envío en woocommerce o si tienes instalado algún plugin de chilexpress lo más probable es que al cambiar de región se quede eternamente "pensando" porque no encuentra conexión con chilexpress para entregar un valor de despacho.
Ahora, si se queda pegado cuando le haces click al botón "realizar pedido" ahí puede haber un problema con webpay.
Saludos.

**Comment by almagency** [comment]
> Hola @almagency creo que tu problema es ajeno al plugin de webpay.. debes buscar el problema en tu configuración de zonas de envío en woocommerce o si tienes instalado algún plugin de chilexpress lo más probable es que al cambiar de región se quede eternamente "pensando" porque no encuentra conexión con chilexpress para entregar un valor de despacho.
> Ahora, si se queda pegado cuando le haces click al botón "realizar pedido" ahí puede haber un problema con webpay.
> Saludos.

Hay varios clientes donde nos aparece que sus compras están canceladas, pero al revisar en webpay, las transacciones si han sido llevadas a cabo. Esto nos está generando mucha confusión para realizar los pedidos de manera rápida, ya que tenemos que revisar tanto los pedidos en estado “procesando”,  como los cancelados y fallidos, para que no se nos pasen los pagos que se han efectuado.

**Comment by almagency** [comment]
Hay varios clientes donde nos aparece que sus compras están canceladas, pero al revisar en webpay, las transacciones si han sido llevadas a cabo. Esto nos está generando mucha confusión para realizar los pedidos de manera rápida, ya que tenemos que revisar tanto los pedidos en estado “procesando”,  como los cancelados y fallidos, para que no se nos pasen los pagos que se han efectuado.

**Comment by jprush76** [comment]
Hola @almagency eso pasa en versiones antiguas del plugin. Tuve el mismo problema en tiendas de clientes, pero actualizando el plugin se solucionó. Saludos.

**Comment by jprush76** [comment]
> Hay varios clientes donde nos aparece que sus compras están canceladas, pero al revisar en webpay, las transacciones si han sido llevadas a cabo. Esto nos está generando mucha confusión para realizar los pedidos de manera rápida, ya que tenemos que revisar tanto los pedidos en estado “procesando”, como los cancelados y fallidos, para que no se nos pasen los pagos que se han efectuado.

Hola @almagency eso pasa en versiones antiguas del plugin. Tuve el mismo problema en tiendas de clientes, pero actualizando el plugin se solucionó. Saludos.

**Comment by gonzunigad** [comment]
Hola @almagency ¿pudiste resolver el problema actualizando el plugin?

**Comment by almagency** [comment]
Hola no nada q ver tuve q hacer  un script para jacer un reload a la pagina
y se arregla pero no me airve xq borra los campos de verdad necesito
ayudaaaaaaa

**Comment by gonzunigad** [comment]
Hola @almagency. Revisamos en varios wodpress que instalamos desde cero y este error no ocurre, por lo que es muy probable que no sea un problema del plugin. 
Nos podría ayudar si nos das información para que podamos replicar el problema :). So podemos replicarlo, podemos entender si hay algo que podamos hacer para resolverlo en el código.
