### ISSUE TITLE
En órdenes grandes, el estado "Procesando" puede dar una vista equivocada al cliente

### ISSUE THREAD

**Issue by svaldesm** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#93]
Al hacer una compra de muchos productos, al retornar, primero pasa al estado "Procesando", que en nuestro caso (y creo que en la mayoría de los casos) no es el estado final del pedido. 
Al retornar en ese estado, el cliente no es llevado al thank-you page en caso que la orden demore mucho. Esto provoca que alguien que hizo una transacción grande piense que no se completó o que hubo un error. 

Los pasos para reproducir serían hacer una compra muy grande con Transbank y retornar al sitio (podemos probar en mi sitio si quieren)

WP: 5.3.2
WC: 3.9.1
TBK: 2.5.2
Cache: Varnish + WP Rocket (el issue también está reportado en el lado de WP Rocket, que hace más lenta aún la transacción: https://github.com/wp-media/wp-rocket/issues/2287)

**Comment by gonzunigad** [comment]
Hola @svaldesm. Gracias por notificar el issue. Revisando el código, aunque la compra no lleve al thank you page, de igual forma se actualiza el estado de la transacción. 

![image](https://user-images.githubusercontent.com/1103494/75711098-8e4ca100-5ca4-11ea-9aff-f3ccc0670aa7.png)
Desde la administración se puede configurar en que estado dejar la orden luego de ser pagada. ¿Esto soluciona el problema planteado?

**Comment by svaldesm** [comment]
Hola @gonzunigad perdona la demora

La verdad es que no la soluciona, porque si bien la información que queda en el backend es correcta, el cliente no sabe si la orden finalizó bien o no. Recibirá el correo de confirmación, pero lo demás es bien raro. Nos pasa que nos escriben por lo mismo "resultó el pago? porque no me apareció que si"

Saludos!
