### ISSUE TITLE
Estatus predeterminado

### ISSUE THREAD

**Issue by melvisnap** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#94]
Hola, este no es un bug, es más bien una oportunidad de mejora.

De seguro aún hay sitios con versiones antiguas de este plugin, considerando esto y los cambios ´ya no tan recientes´ relacionados al cambio de estatus al retornar del pago exitoso, creo que sería mejor idea que el estado por defecto sea ´wc-processing´, ya que es el estado habitual del flujo de WooCommerce y de cualquier otra pasarela de pago.

Esto podría servir para evitar crear confusión a la hora de actualizar de versiones antiguas que no incluían esta opción, o incluso nuevas integraciones. 

Saludos.

**Comment by gonzunigad** [comment]
Hola @melvisnap . Gracias por la recomendación. ¿En que estado quedó esa configuración cuando actualizaste?

**Comment by melvisnap** [comment]
Hola, @gonzunigad 

Quedó en pendiente, según entiendo ese es el estado por defecto, yo leí el changelog antes de instalar así que lo cambié luego de actualizar.

**Comment by TCattd** [comment]
Confirmo.

Actualicé un sitio desde la versión 2.0.4 del plugin, a la versión 2.5.2 hoy, y el estado que quedó por defecto fue el Pendiente: https://tppr.me/kACjT

Y toda la razón, el estado habitual de los gateway de WooCommerce luego de procesar un pago, debiese ser el estado Procesando.

Ver: https://docs.woocommerce.com/document/managing-orders/
Puntualmente: https://docs.woocommerce.com/wp-content/uploads/2013/05/woocommerce-order-process-diagram.png

**Comment by gonzunigad** [comment]
Excelente. Vamos a aplicar el cambio. Muchas gracias por la contribución 🎉
