### ISSUE TITLE
Compatibilidad Woocommerce 4.0

### ISSUE THREAD

**Issue by Richardmaximun** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#99]
Estimados (as),

Alguien ha probado el pluggin con el nuevo Woocommerce 4.0? 

Los requisitos de Transbank Webpay dicen "Woocommerce 3.4 o superior" pero el chequeo de Wocommerce 4.0 dice que no es compatible. 

Alguien me puede confirmar sí o no, por favor?

Saludos

**Comment by melvinvita** [comment]
No he tenido problemas con 4.0. 

Igual te recomiendo probar en un staging y hacer respaldo en el sitio en producción antes de implementarlo.

**Comment by Richardmaximun** [comment]
> No he tenido problemas con 4.0.
> 
> Igual te recomiendo probar en un staging y hacer respaldo en el sitio en producción antes de implementarlo.

Sí. Eso estoy haciendo justo ahora pero queria saber la experiencia que pudieran haber tenido los de la comunidad.

Muchas gracias

**Comment by gonzunigad** [comment]
Hola @Richardmaximun. Gracias por crear el issue. Acabamos de probar y también nos funciona correctamente en WooCommerce 4.0, por lo que lanzaremos un nuevo release indicando que funciona correctamente con esta última versión.

**Comment by Richardmaximun** [comment]
> Hola @Richardmaximun. Gracias por crear el issue. Acabamos de probar y también nos funciona correctamente en WooCommerce 4.0, por lo que lanzaremos un nuevo release indicando que funciona correctamente con esta última versión.

Gracias a uds @gonzunigad . Confirmo que tambien me funciona pero estamos generando compras aleatorias masivas en modo desarrollo para ver si salta algun error. La idea es que no pase en produccion. Tu sabes

Saludos

**Comment by gonzunigad** [comment]
Ya está publicada la versión 2.6.0 que indica el soporte para WooCommerce 4.0 👌
